### ISSUE TITLE
no icon for Azure Code Samples entity in Find Actions dialog

### ISSUE THREAD

**Issue by kirfalk** [JetBrains/azure-tools-for-intellij#12]
Rider 2018.2.3 RTM #182.4231.496
Azure plugin : 3.11.0
Invoke Ctrl-Shift-A (Cmd-Shift-A) for Find Action popup. Type 'pl'
![no_icon_azurepl](https://user-images.githubusercontent.com/5609871/45494652-32bde900-b77a-11e8-9b9a-8f32012eacfd.png)

**Comment by sdubov** [comment]
There are two missing icons: "Azure Code Samples" and "Azure". Fixed in ff3b24ef7ecc0e501acf3450736c258ae94adc71

**Comment by sdubov** [comment]
Fixed in ff3b24ef7ecc0e501acf3450736c258ae94adc71
