### ISSUE TITLE
performance impact on Rider's welcome screen if I have Azure plugin installed into Rider

### ISSUE THREAD

**Issue by kirfalk** [JetBrains/azure-tools-for-intellij#13]
Rider 2018.2.3 RTM #182.4231.496
Azure plugin : 3.11.0
simply install Azure plugin and start Rider. You can't select any recent projects immediately.
Deactivation / Uninstall helps me

**Comment by sdubov** [comment]
Fixed in 4949fa74c741bf92077659df1b34f44100b06812
