### ISSUE TITLE
[Discussion] Move project selector to the top at the configuration window

### ISSUE THREAD

**Issue by ForNeVeR** [JetBrains/azure-tools-for-intellij#132]
Today user contacted me and told that he couldn't set up a project for publishing. And he attached a screenshot like that:

![image](https://user-images.githubusercontent.com/92793/50230857-8ca7fd80-03be-11e9-8941-3cdd56f77965.png)

For some reason, it was unobvious for the user that we have scrolling in the window, and that he has to scroll the settings to get to the project list.

Could we move the project selector to the top? It will be better for new users and I don't think that it will become significantly worse for the old users who already set the configuration.

**Comment by sdubov** [comment]
I think we could reduce the table height to make sure project combo box is visible. We need to play a bit with controls placement and select the right one. Will take a look.

**Comment by sdubov** [comment]
Fixed in 183.1 branch in scope of commit ed77f01a9f5a52604238525c4002581b24ca77d7. Added the logic that resize existing web apps table based on parent window height. Now, we have a "project" combobox always visible under the existing web apps table.
