### ISSUE TITLE
Publish web app to Azure using a publish profile

### ISSUE THREAD

**Issue by DavidZizu** [JetBrains/azure-tools-for-intellij#141]
I would be really nice if user could publish a web app to Azure using a publish profile provided by Azure.

**Comment by maartenba** [comment]
Does this work for your scenario?
https://blog.jetbrains.com/dotnet/2018/07/25/publishing-asp-net-core-web-applications-iis-ftp-rider-2018-2/

**Comment by DavidZizu** [comment]
@maartenba oh, thank you! I somehow didn't notice that feature

**Comment by maartenba** [comment]
Awesome! Let us know if anything is missing there.
