### ISSUE TITLE
[Azure Explorer] Is it possible to connect Storage Account using Name and Key?

### ISSUE THREAD

**Issue by adrtarnowski** [JetBrains/azure-tools-for-intellij#142]
I'm able to connect Storage Account using Account name and Account key in Microsoft Azure Storage Explorer. Unfortunately, I don't see that functionality in Rider so Are you going to add connecting via key feature?

**Comment by maartenba** [comment]
This is currently in the `191` branch, and will surface in Rider 2019.1. Stay tuned!

(duplicates #120)
