### ISSUE TITLE
Allow publishing to App Service with kind "API"

### ISSUE THREAD

**Issue by trenoncourt** [JetBrains/azure-tools-for-intellij#149]
Hi,

I cannot make a deployment with App service with kind api.
Only web app are listed in App service.

**Comment by maartenba** [comment]
https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider/reviews#review=49901

**Comment by adrynalyne** [comment]
Even though this is closed and listed as available in the Feb. 19th release, I still do not have the ability to display and publish to API type App Services.

**Comment by maartenba** [comment]
It's in the Early Access Preview version of Rider (,which will release as stable near the end of the month).

You can try it if you would like - www.jetbrains.com/rider/eap
