### ISSUE TITLE
Web app selected as deploy destination is not preserved

### ISSUE THREAD

**Issue by disaverio** [JetBrains/azure-tools-for-intellij#170]
In menu `Run` -> `Edit configurations` create a new `Azure Publish to Web App`. Then on the right pane (in `Web App Configuration` tab) select `Use Existing Web App`.
You need to have more than one web app, in the list below: then you change the order of the list (e.g. sorting by name), and select one of them.
Save (Ok/Apply) and close. If you re-open the configuration in `Edit configurations` the selected web app is not the one you selected (actually the selected one is the one of the same position: i.e. the selected index is stored).

⚠⚠⚠ **the wrong web app is used for the deploy if you launch it!!!**

**Comment by maartenba** [comment]
Hi @disaverio - this has been fixed in the upcoming 2019.1 release. Stay tuned!

**Comment by disaverio** [comment]
Well, good to know

**Comment by sdubov** [comment]
Fixed in 5854319cddcda4961d90dc760ba30e368c53447c
