### ISSUE TITLE
Cannot connect to Azure Storage Emulator with v3.22.0-2019.1

### ISSUE THREAD

**Issue by vasileciumac** [JetBrains/azure-tools-for-intellij#205]
Cannot connect to Windows Azure Storage Emulator 5.3.0.0 with the Azure explorer tool from the v3.22.0-2019.1

**Comment by sdubov** [comment]
@vasileciumac, could you please post an error with stack trace you are getting when connecting?

**Comment by vasileciumac** [comment]
There is no error because this feature is not available in the Plugin for Intellij Idea. It is only available in the Raider version of the plugin.
Screenshot from the Rider Azure Explorer:
![image](https://user-images.githubusercontent.com/34277209/58170520-e4ab9e80-7c93-11e9-9727-684f80273a71.png)

The menu entry "Attach external storage account" is missing in the Intellij IDEA

Regards

**Comment by maartenba** [comment]
@sdubov Looks like an issue for the IntelliJ plugin (not the Rider one).
@vasileciumac would you mind creating a feature request at https://github.com/microsoft/azure-tools-for-java ?

**Comment by sdubov** [comment]
Got it. @vasileciumac, yes, it was the feature we add in Rider plugin - https://github.com/JetBrains/azure-tools-for-intellij/issues/120

**Comment by vasileciumac** [comment]
@sdubov Thanks for the answer ;)
