### ISSUE TITLE
Enable protocol and backend extensions in plugin

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#234]
We should enable backend and protocol extension in plugin. This will allow us to:
- Re-write Function gutter mark
- Add completion in forms
- Enable analysis
- etc...

**Comment by maartenba** [comment]
@sdubov do you think this is one we can start looking into after all?

**Comment by sdubov** [comment]
I think it is reasonable to do if we expect to support more analysis inside a plugin. + I think it would be good plan to re-write function gutter marks detection on a backend.

**Comment by sdubov** [comment]
@maartenba, Do you have anything blocked by this task? I can enable backend in couple days.

**Comment by maartenba** [comment]
Nothing blocked, but indeed gutter marks and some more language intelligence would be nice. Also we could do gutter marks for F# then :)
