### ISSUE TITLE
Publish azure web app does not work

### ISSUE THREAD

**Issue by Krangth** [JetBrains/azure-tools-for-intellij#236]
Update Rider today. Plugin Version says: 3.26.0.528-2019.2

When I start the publish to azure, all of the usual messages appear in the console that I have seen many times before. However, the site only stops and starts. The code is never updated. The same old version of the site remains.

**Comment by maartenba** [comment]
Should be released soon. Thanks for reporting, @Krangth!

**Comment by Krangth** [comment]
Works great again! Thank you so much for the quick turn around.
