### ISSUE TITLE
Azure Functions 3.0 tracking issue

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#240]
See https://github.com/Azure/app-service-announcements/issues/200

**Comment by maartenba** [comment]
https://dev.to/azure/develop-azure-functions-using-net-core-3-0-gcm

Seems to work by updating the `Microsoft.NET.Sdk.Functions` package version to `1.0.30-beta2`, and targeting `netcoreapp3.0`.

E.g.:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netcoreapp3.0</TargetFramework>
        <AzureFunctionsVersion>2</AzureFunctionsVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.30-beta2"/>
    </ItemGroup>
    <ItemGroup>
        <None Update="host.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="local.settings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>
</Project>
```

**Comment by jetersen** [comment]
Half truth @maartenba Rider seems to ignore `AzureFunctionsVersion` when set to `v3-preview` or user at least have to point to a different azure-functions-coretools version.

There seems to be no way for rider to select/download the preview version 
`Azure Functions Core Tools (3.0.1740 Commit hash: 0b841ce061d005a05af8bb57a341989788266298)`

**Comment by maartenba** [comment]
Regarding ` AzureFunctionsVersion = v3-preview`, what do you mean by "ignored"?

Regarding tools: these are downloaded from [their GitHub releases page](https://github.com/Azure/azure-functions-core-tools/releases), which currently does not list the preview version.

However, it's possible to install the tools via NPM (`npm install -g azure-functions-core-tools@preview`) and then configure Rider to pick the tools up from the install path (under **Tools \| Azure \| Functions**), e.g. `C:\Users\{username}\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin`.

![image](https://user-images.githubusercontent.com/485230/67152100-15affe00-f31c-11e9-9432-7d912a25b1a9.png)

**Comment by jetersen** [comment]
I meant it was ignored until you realize that you need to update tools path 😅
