### ISSUE TITLE
Support PublishSettings file

### ISSUE THREAD

**Issue by sbyzova** [JetBrains/azure-tools-for-intellij#244]
Support a way to use publishsettings file.
https://dailydotnettips.com/getting-azure-app-services-publishing-profile-inside-visual-studio-itself/

**Comment by sbyzova** [comment]
https://twitter.com/MikeMcLoughlin/status/1162311643415625729

**Comment by maartenba** [comment]
You can use the "Publish to IIS" configuration for this.
![image](https://user-images.githubusercontent.com/485230/65150563-aeedab00-da24-11e9-86f7-c5b247b3607c.png)
