### ISSUE TITLE
Cannot add F# file to an F# Azure Functions project

### ISSUE THREAD

**Issue by sbyzova** [JetBrains/azure-tools-for-intellij#250]
1. create an F# Azure FUnctions project from the template
2. try to add an F# file to this project
result:
-file is not added
-error message "Sequence contains no elements" appears.
<img width="836" alt="Screenshot 2019-10-05 at 23 17 55" src="https://user-images.githubusercontent.com/52917649/66260360-683ed580-e7c6-11e9-8393-39c2e1739c6e.png">

**Comment by maartenba** [comment]
@auduchinok would you have any idea where this can come from? (sample project attached, adding any F# file shows this error message)
[Company.FunctionApp1.zip](https://github.com/JetBrains/azure-tools-for-intellij/files/3694177/Company.FunctionApp1.zip)

**Comment by maartenba** [comment]
Looks like https://youtrack.jetbrains.com/issue/RIDER-31074

**Comment by auduchinok** [comment]
Yes, it's the one. I'll take a look, thank you.

**Comment by maartenba** [comment]
@sbyzova Looks like it will be fixed with 2019.3
