### ISSUE TITLE
Debug throws exception

### ISSUE THREAD

**Issue by mvsmal** [JetBrains/azure-tools-for-intellij#251]
I have a Function App with several functions. I am using 2 types of triggers: HttpTrigger and ServiceBusTrigger. When I try to Debug the app, it doesn't run, but stops with ArgumentNullException. However if just run the app, it works, and I can even attach to function `host` process and debug it. But it is very annoying.
![image](https://user-images.githubusercontent.com/3872761/66500792-717bbb00-eac2-11e9-9954-e57331b08ba8.png)

Similar issue, where guys mention ServiceBus:
https://github.com/Azure/azure-functions-core-tools/issues/1409
I am not sure where the problem really is, in the plugin or azure-functions-core-tools.

I have the latest versions of Rider, Azure Toolkit plugin and azure-functions-core-tools.

**Comment by maartenba** [comment]
Would you happen to have a small repro project?

**Comment by mvsmal** [comment]
I couldn't reproduce it in another project. Tried to delete .idea folder for the existing one and it helped. No exception anymore. Thanks.
