### ISSUE TITLE
Remove additional files at destination

### ISSUE THREAD

**Issue by kwasak** [JetBrains/azure-tools-for-intellij#261]
I noticed that after publishing to Azure Functions from Rider that older functions previously created still remain in Azure.

Visual Studio gives you the option to delete older files by essentially performing a "clean publish" with an option called "Remove additional files at destination".

![Remove additional files at destination](https://i.stack.imgur.com/HbzWk.png)

**How would I delete older functions when publishing to Azure in Rider?**

Thanks in advance!

**Comment by maartenba** [comment]
Not currently, will investigate if we can add this.

**Comment by maartenba** [comment]
@kwasak Rider makes use of [ZIP deployment](https://github.com/projectkudu/kudu/wiki/REST-API#zip-deployment-preview). The Azure docs state that [existing files will be deleted](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url), with one exception:

> Deletion of files no longer in the build: When a new build is deployed with zipdeploy, files and directories that were created by the previous deployment but are no longer present in the build will be deleted. *Any other files and directories found in the site that aren't being overwritten by the deployment, such as those placed there via FTP or created by your app during runtime, will be preserved.*

If you have previously deployed this function app using e.g. Visual Studio Web Publish, it seems App Service will treat those files as "not part of ZIP deploy" and preserve them.

ZIP deploy should thus always remove older files, unless they were already in your App Service before the first ZIP deploy happened.

For Rider, it would be impossible to remove "older files" without violating the fact that the app can write files into the file system (or things like site extensions that reside `bin`), hence it seems best to do a manual cleanup once, and then always deploy using Rider's ZIP deploy.

**Comment by kwasak** [comment]
Ok thank you for this, I did previously publish in Visual Studio, I'll look into it deleting the files manually.
