### ISSUE TITLE
Cannot run Fabric Application in Rider

### ISSUE THREAD

**Issue by melgaray** [JetBrains/azure-tools-for-intellij#262]
Is it possible to run .sfproj from within Rider? I installed the Azure toolkit plugin but that doesn't seem to help. If not, are there any workarounds?
Thanks,

**Comment by maartenba** [comment]
Right now, there is no support for SF in Rider. A tracking issue is here: https://youtrack.jetbrains.com/issue/RIDER-10370 - feel free to +1 and add your comments there.
