### ISSUE TITLE
Merge C# and F# Azure Functions

### ISSUE THREAD

**Issue by davidhenley** [JetBrains/azure-tools-for-intellij#268]
Azure Functions in Rider 2019.2.3 has two separate items in the list. (AzureFunctions & Azure Functions) This should be merged then allow language switching.

![Screen Shot 2019-12-09 at 3 08 38 PM](https://user-images.githubusercontent.com/15056748/70473019-d25d4a80-1a95-11ea-9c2d-98462ac0a5a4.png)

![Screen Shot 2019-12-09 at 3 08 30 PM](https://user-images.githubusercontent.com/15056748/70473026-d4270e00-1a95-11ea-8c79-67827c34f448.png)

**Comment by maartenba** [comment]
This has been PR-ed against the Microsoft repository a while ago, yet not yet shipped with the functions core tools it seems. Opened an issue for that here: https://github.com/Azure/azure-functions-core-tools/issues/1699

**Comment by davidhenley** [comment]
Ok thanks. I searched but didn't see the relationship between the two.

**Comment by maartenba** [comment]
No worries :) Hoping the bundled templates get updated at some point.

**Comment by maartenba** [comment]
Looks like an update of the core tools shipped with new templates.

**Comment by davidhenley** [comment]
@maartenba Have you tested this? Even with all the updates I am still seeing the same in the project templates.

**Comment by maartenba** [comment]
Yes, have to use the v3/pre-release core tools though
