### ISSUE TITLE
Run .Net 4.7.2 Azure Functions

### ISSUE THREAD

**Issue by crosswins** [JetBrains/azure-tools-for-intellij#272]
Using the Edit Configurations I see no way to configure to run/debug Azure Functions running under .Net 4.7.2. I can use the new Azure Functions templates for our .Net Core projects but this is specifically .Net 4.7.2

**Comment by maartenba** [comment]
Thanks, @crosswins !

This will require an update to Rider itself, I logged an issue at https://youtrack.jetbrains.com/issue/RIDER-37080 and am working on a fix which will should make it into Rider 2019.3.1.

**Comment by maartenba** [comment]
Going to close the issue here, patch in Rider has been merged and should appear in the next release. Thanks again for reporting!
