### ISSUE TITLE
Functions:  Autodetect and use version of tools

### ISSUE THREAD

**Issue by tjaart** [JetBrains/azure-tools-for-intellij#278]
The core tools path has to be manually specified in the plugin configuration. 

Please add functionality to 
- Autodetect the tools version from the project
- Automatically download tools versions as necessary
- Run each project with correct version

**Comment by sdubov** [comment]
@tjaart, thank you for your report. 

We already have a logic to detect if you do not have a core tool or if there is a newer version available and helps you download it through IDEA Notifications mechanism or you can do it manually from Settings.

I like the idea about auto detection user's installation. We can extend the logic to check this into a Plugin to simplify the configuration steps.

As for auto-download, I would like to explicitly notify a user about what we expect to do rather then doing any downloads on user's box silently.

**Comment by sdubov** [comment]
Split the original issue on a sub-tasks:
Auto-detect: https://github.com/JetBrains/azure-tools-for-intellij/issues/293
Version to run: https://github.com/JetBrains/azure-tools-for-intellij/issues/294

**Comment by maartenba** [comment]
Closing this issue for now, after splitting in 2 separate issues.
