### ISSUE TITLE
Multiple "Azure Functions host" run configuration group are created when launching function from gutter mark

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#285]
Steps to reproduce:
1. Create multiple functions
2. Run them from gutter mark in Editor
3. Open Run Configurations

Expected: All function run configurations are combined under **Azure Functions host** run configuration group.
Actual: Each function run configuration is stored under its own **Azure Functions host** group.

<img width="354" alt="DuplicatedFunctionRunConfig" src="https://user-images.githubusercontent.com/6064345/79044641-e4e7bc00-7c0e-11ea-9a9e-ee0f12c6f7c7.png">

**Comment by sdubov** [comment]
Fixed in https://github.com/JetBrains/azure-tools-for-intellij/pull/286

**Comment by maartenba** [comment]
Awesome!
