### ISSUE TITLE
Functions: Run project against a function core tool version defined in proj file

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#294]
Original request - https://github.com/JetBrains/azure-tools-for-intellij/issues/278

Project file can specify multiple functions with different core tools version:
```
<PropertyGroup>
    <AzureFunctionsVersion>V3</AzureFunctionsVersion>
</PropertyGroup>
```
We need to define a plugin behaviour for this case and check if we need to run against a specified version.

**Comment by maartenba** [comment]
Been doing some digging into how VS does things:
* Based on `AzureFunctionsVersion`, the tools version is determined
* Tools are then matched to the feed URL described in https://github.com/Azure/azure-functions-tooling-feed. The matching tools version is downloaded to `%APPDATA%\azurefunctionstools\` and used to launch the functions application
* Some more background in https://newbedev.com/visual-studio-2019-re-downloads-azure-function-cli-tools

I think we should do something similar in the future.

**Comment by SeanFeldman** [comment]
![image](https://user-images.githubusercontent.com/1309622/147832546-f2e84088-d5e2-4271-989d-435f675144bb.png)

**Comment by maartenba** [comment]
Also should cut down on social media 😅

**Comment by maartenba** [comment]
Been thinking about this a bit, and considering the following in terms of design. What do you think, folks?

## Proposed behaviour

1. By default, Rider would self-manage Azure Functions core tools based on the `AzureFunctionsVersion` MSBuild property for your project. It will always download the latest version for a specific tag from the [tooling feed](https://functionscdn.azureedge.net/public/cli-feed-v4.json).
2. These defaults won't need any additional changes - it will "just work ™️". Configuration will be provided, though.
3. The templates in the new Solution/new Project dialog would always use the newest version of the templates. That is, the templates that are configured for the latest tag, e.g. "v4".

## Proposed configuration options

Of course, everyone wants customization options, so the settings would provide these. An ASCII-art mockup of the settings (`Tools | Azure | Functions`) for various states.

### Everything managed by Rider

By default, Rider will manage things. It will download newer versions of the core tools when needed.
* Idea is to do this either on solution load, or the first time you run the project. Any preferences?
* Download path would be in your `$HOME` by default, or in a path that you select in the settings.

Settings page:

```
| Azure Functions version | Tools path       |
|-------------------------|------------------|
| v1                      | Managed by Rider |
| v2                      | Managed by Rider |
| v3                      | Managed by Rider |
| v4                      | Managed by Rider |

Azure Functions Core Tools will be downloaded to [$HOME/RiderAzureFunctions][..]
```

### Custom options

You will be able to set custom paths for some versions. Here's a nice mix of what this could look like:

```
| Azure Functions version | Tools path       |
|-------------------------|------------------|
| v1                      | Managed by Rider |
| v2                      | /usr/bin/somepath |
| v3                      | /usr/bin/someotherpath |
| v4                      | Managed by Rider |

Azure Functions Core Tools will be downloaded to [$HOME/RiderAzureFunctions][..]
```

## Other considerations

* Do we need to show settings for all tags in the feed?
  * Pro: newer versions will automatically show up automatically
  * Con: newer versions will automatically show up automatically, and may not be compatible with Rider yet

Any opinions/additional ideas welcome :-)

**Comment by SeanFeldman** [comment]
The proposed approach is quite aligned with what I'd need for my projects.

>By default, Rider will manage things. It will download newer versions of the core tools when needed.
>
>- Idea is to do this either on solution load, or the first time you run the project. Any preferences?

Whatever causes Rider to be less laggy during start-up.

>- Download path would be in your $HOME by default, or in a path that you select in the settings.

I like that but recently $HOME starts to feel like a kitchen sink. Rather than seen `$HOME/RiderAzureFunctions` I'd be more appreciative if Rider would keep it tidy with something like `$HOME/Rider/AzureFunctions`, allowing future things to be stored under `$HOME/Rider` as well.

> Do we need to show settings for all tags in the feed?
> - Pro: newer versions will automatically show up automatically
> - Con: newer versions will automatically show up automatically, and may not be compatible with Rider yet

I don't know if I want to see all the options other than the latest ones TBH. I might be not thinking it through as I should but don't remember ever going back to an older version. Mostly doing the opposite to ensure the runtime has everything up-to-date.

**Comment by maartenba** [comment]
Regarding "all options", the question is whether the Azure Functions Core Tools feed's `-*` versions should be configurable or not... Here's the current list:

![image](https://user-images.githubusercontent.com/485230/148379740-ab6a0727-e12f-4c67-a0c1-0459a1e77705.png)

**Comment by SeanFeldman** [comment]
<img src="https://c.tenor.com/cKf7FeLja6cAAAAC/cant-wait-excited.gif"/>
