### ISSUE TITLE
Functions: Debugging "Only in my code" does not work

### ISSUE THREAD

**Issue by UnoSD** [JetBrains/azure-tools-for-intellij#304]
Hi, I hope this is the right place for this issue.

When I debug an Azure Function from Rider and I have "Only in my code" selected in the exceptions breakpoints, the execution never stops on any exception.

If I disable it, it works, but obviously interrupts the debug experience several times for handled exceptions in the hosting framework.

Rider 2020.1.3
Azure toolkit 3.35.0.651-2020.1
Arch Linux, .NET Core 3.1
Function tools 3.0.2534

Thank you.

**Comment by maartenba** [comment]
@UnoSD could you try with the latest Rider 2020.2 EAP + Azure Plugin? This should be fixed now.
