### ISSUE TITLE
Add Dockerfile with build container definition into the plugin repo

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#308]
Currently, we use a container from `https://hub.docker.com/r/ivanpashchenko/rider-plugins-docker-image/dockerfile` to build the plugin. We are going to use a backend in plugin in nearest time (#234) that means that we will need to extend this container to setup `dotnet`, etc. We should rather create a Dockerfile with container definition and store it inside a plugin repo.

Please see all related steps in https://youtrack.jetbrains.com/issue/RIDER-45471

**Comment by maartenba** [comment]
(done, right?)

**Comment by sdubov** [comment]
Yes. Thank you.
