### ISSUE TITLE
Migrate TimerTrigger function app completion logic to backend

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#310]
Currently, we have a logic for TimerTrigger function app schedule expression on a frontend - `AzureFunctionsTimerTriggerCronInspection`. We need to migrate it to backend when #234 is merged into `202` branch.

Please see notes in #297 from @maartenba.

**Comment by sdubov** [comment]
#234 is merged into 202.

**Comment by maartenba** [comment]
Might be useful for tooltips/hover explanation of the crontab: https://github.com/bradymholt/cron-expression-descriptor (or handle on front-end using existing description library)

**Comment by sdubov** [comment]
Yep. I looked through this package too. The issue with this package is that the signed version is pretty old (1.<something>). The thing is - we actually do not need to get a description. We show a static values in a completion popup and do not update it. So, we can statically define all necessary descriptions. The only thing we need this library is parsing for inspections. NCrontab provide necessary parsing errors that can be shown in tooltips.
