### ISSUE TITLE
Azurite tools (cross-platform storage emulator)

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#312]
To run Azure functions (or for other reasons), a local storage emulator is required.

There is [Azurite](https://github.com/Azure/Azurite), a lightweight storage emulator, that can be used, either as an npm package or using Docker:

```
# NPM
npm install -g azurite
azurite
# or: azurite --location <path-to-workspace>
```

It would be nice if we could add functionality to start/stop/reset the emulator from within Rider.

**Comment by vdurante** [comment]
If anyone else (like me) got here looking for a solution, I have created an External Tool with the following config:

- Program `C:\Windows\System32\cmd.exe`
- Arguments `/c start /B "" "C:\Program Files\nodejs\azurite.cmd" -s -l c:\azurite -d c:\azurite\debug.log` (you should adjust the arguments to fit your desire)

Just add it as a Before Launch step.

**Comment by maartenba** [comment]
Another option is to create a run configuration/Docker - https://blog.maartenballiauw.be/post/2020/06/08/run-azurite-in-docker-with-rider-and-keep-azure-storage-data-local-to-a-solution.html

We'll get proper support done, too :)

**Comment by maartenba** [comment]
@vdurante Can you check the above PR/screenshots/assumptions and add your thoughts?

**Comment by vdurante** [comment]
@maartenba sorry to bother, but do you intend to implement something similar for Azure Storage Emulator? Since Azurite doesn't implement the whole Azure Storage Emulator API, it could be nice to be able to configure preferred Functions storage emulator on the settings.

Just as an example, [Azurite doesn't support Table Storage](https://github.com/Azure/Azurite/issues/428) which is required for developing Durable Functions.

Thank you!

**Comment by maartenba** [comment]
@vdurante We'll be integrating Azurite as-is, so not going to create our own if that is what you are asking :-)

Table storage is a bummer for Azure Functions indeed, but that's outside of the scope for tooling support. It's still possible to use regular Azure Storage Emulator, integrating Azurite makes things a bit easier for those new to Azure etc.

That said, let me chime in to that Azurite issue as well, would love to see table storage support there.
