### ISSUE TITLE
Migrate AzureFunctionsVersionInspection (MSBuild) to back-end

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#314]
https://github.com/JetBrains/azure-tools-for-intellij/blob/202/PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/codeInspection/msbuild/AzureFunctionsVersionInspection.kt

cc @sdubov

**Comment by maartenba** [comment]
Not sure if this needs to be BE or FE

**Comment by sdubov** [comment]
Rider have csproj inspections on frontend similar to our Function App Version due to missing PSI on a backend.
