### ISSUE TITLE
Solution/project name causes Rider to not recognize it as an Azure Function

### ISSUE THREAD

**Issue by vdurante** [JetBrains/azure-tools-for-intellij#315]
Example 1:

![image](https://user-images.githubusercontent.com/5401232/84156619-1b3f8d00-aa40-11ea-99d3-bebe7b539f54.png)

Example 2

![image](https://user-images.githubusercontent.com/5401232/84156640-24c8f500-aa40-11ea-8c9f-1b6d2ebbbe37.png)

**Comment by maartenba** [comment]
For example 1, could you share the `.csproj` contents? We treat a class library as an Azure Functions project when the following is true:

* `AzureFunctionsVersion` element is in the project file
* `Microsoft.NET.Sdk.Functions` is referenced
* `host.json` is in the project

**Comment by vdurante** [comment]
@maartenba thank you for the answer. The 3 points above were satisfied. I created the solution from Rider itself. After I manually added a Function it started working again. No more issues ever since.
