### ISSUE TITLE
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by libin049** [JetBrains/azure-tools-for-intellij#323]
![image](https://user-images.githubusercontent.com/7247717/85117078-db9f4f00-b250-11ea-8003-b1a44ed35524.png)

**Comment by maartenba** [comment]
@libin049 looks like these are coming from the IntelliJ plugin - could you use the `Report to Microsoft` button at the bottom? This will include more detailed troubleshooting information (and send it to the right repository).

Thanks for reporting!
