### ISSUE TITLE
Remove dependencies to JavaFX in source code

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#329]
Idea SDK 202 has removed dependency from JavaFX. We have `com/microsoft/azuretools/ijidea/ui/LoginWindow.java` in common code that has dependencies to javafx module. We need to fix it using one of provided solution:
- Rewrite the code using JCEF
- Use Swing
- Add dependency to JavaFX Runtime plugin (https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins)

**Comment by prigara** [comment]
Here you can find more details about using JCEF in the IntelliJ IDEA Platform: https://www.jetbrains.org/intellij/sdk/docs/reference_guide/jcef.html

**Comment by sdubov** [comment]
Here is the related ticket with login options in the original plugin repo - https://github.com/microsoft/azure-tools-for-java/issues/1877.

Based on this issue, `LoginWindow`, that uses JavaFX imports, is not used anymore in the plugin for login. We can close the ticket.

**Comment by sdubov** [comment]
Sorry, still need to fix this since we have compilation issues if javafx is not bundled anymore. LoginWindows is still here even if it is not used. We can re-write this code with new JCEF bundled framework.
