### ISSUE TITLE
Azure explorer blank and can't login on MacOS

### ISSUE THREAD

**Issue by ShaunEgan** [JetBrains/azure-tools-for-intellij#332]
I am very new to Rider and Azure, so I may be miss-understanding something - I can't find any reference to this problem so far.

I have installed Azure Toolkit for Rider, and am trying to deploy my function apps. The deploy screen run configuration screen is completely blank:

![run-config](https://user-images.githubusercontent.com/5261827/88273196-1aa24380-ccda-11ea-8ac3-20b58e52d466.png)

Also, I never got to a place to be able to log in to my Azure account, and the Azure explorer is blank:

![azure-explorer](https://user-images.githubusercontent.com/5261827/88273220-2261e800-ccda-11ea-8741-502c4056b8b5.png)

I have tried reinstalling Azure Toolkit for Rider, and I have tried letting it download the latest `azure-functions-core-tools` as well as using the brew installed copy (both of which are the same version: 3.0.2630)

I would love to continue with rider as I have years of experience with Idea, and really dislike Visual Studio on Mac. Deployment to our dev environment is an integral part of my flow, so any suggestions would be greatly appreciated.

**Comment by sdubov** [comment]
Hi @ShaunEgan! Wow! This is really weird. Let's take a look. The explorer should be the entry point for login and should not be blank even when you are not logged in to Azure. Could you please try to call `Azure Sign In...` action directly to make sure it is not the reason: (Shift + Shift) to call search everywhere and search for "Azure Sign In..." action?

**Comment by ShaunEgan** [comment]
Hey! I tried searching for "Azure Sign In" and it also resulted in no results.

**Comment by sdubov** [comment]
Could you please check what Rider and Azure Toolkit plugin version are you using?

**Comment by ShaunEgan** [comment]
Azure Toolkit Plugin: 3.35.0.651-2020.1

JetBrains Rider 2020.1.4
Build #RD-201.8538.1, built on July 3, 2020
Licensed to Rider Evaluator
Expiration date: August 22, 2020
Runtime version: 11.0.7+10-b765.64 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Core 3.1.3
macOS 10.15.5

**Comment by sdubov** [comment]
Just check on the same versions. @ShaunEgan, would you mind to send us Rider logs and report them using the instruction here - https://rider-support.jetbrains.com/hc/en-us/articles/360001079770-How-to-collect-Rider-logs- ?

**Comment by ShaunEgan** [comment]
I have opened a support ticket with the logs, Ill update here if there is a resolution. Thank's for the help!

**Comment by sdubov** [comment]
@ShaunEgan, thank you for sending logs. It makes this clear now. Looks like the issue is related to Azure auth manager logic -  https://github.com/JetBrains/azure-tools-for-intellij/blob/e6b7c2684e1660cd04e7db801aa44f60a2772d77/Utils/azuretools-core/src/com/microsoft/azuretools/authmanage/AuthMethodManager.java#L199 

There is similar opened ticket - https://github.com/microsoft/azure-tools-for-java/issues/4511. I was able to reproduce it. The main reason here is in incorrect JSON that is stored in `AuthMethodDetails.json` (Azure auth details json) local file on sign in attempt. The JSON is created with `null` authMethod that cause an error when reading the data. 

As a workaround until the issue is fixed you can edit your Auth file `/Users/<user_name>/.AzureToolsForIntelliJ/AuthMethodDetails.json` manually and set `authMethod` to `DC` (Device Code) value like this:
```
{"accountEmail":null,"credFilePath":null,"authMethod":"DC","azureEnv":null}
```
Or just delete the file and the plugin should recreate it on further logins.

**Comment by mlabisi** [comment]
Hi there @sdubov! I'd like to hop on to this discussion to see if this issue could be related to the error message I'm seeing? I'm using the Azure Toolkit for Rider on Windows! 
![image](https://user-images.githubusercontent.com/5050718/88859234-2300ef80-d1ae-11ea-8f16-8d18b023e3f8.png)

I was able to login on Friday, but something may have happened over the weekend. This error started popping up on Monday.

**Comment by ShaunEgan** [comment]
The work around got it working for me, much appreciated.

**Comment by sdubov** [comment]
Hey @mlabisi! This is a different issue. Usually it means that java process missing a certificate that is required under the running process. It looks like it is required when login to Azure. Could you please report create a separate ticket and attach Rider logs using the instruction here - https://rider-support.jetbrains.com/hc/en-us/articles/360001079770-How-to-collect-Rider-logs- ? Then I can check a stack traces to understand the issue and help to fix it.

**Comment by mlabisi** [comment]
> Hey @mlabisi! This is a different issue. Usually it means that java process missing a certificate that is required under the running process. It looks like it is required when login to Azure. Could you please report create a separate ticket and attach Rider logs using the instruction here - https://rider-support.jetbrains.com/hc/en-us/articles/360001079770-How-to-collect-Rider-logs- ? Then I can check a stack traces to understand the issue and help to fix it.

Will do! Thanks for your response 😊

**Comment by mlabisi** [comment]
@sdubov [Here](https://github.com/JetBrains/azure-tools-for-intellij/issues/336) it is!

**Comment by maartenba** [comment]
@mlabisi How does this look with 2020.2?

**Comment by mlabisi** [comment]
Yes @maartenba, the issue I mentioned has been fixed! I closed [the issue I made](https://github.com/JetBrains/azure-tools-for-intellij/issues/336) a few days ago. Thanks again for the help!

**Comment by maartenba** [comment]
@ShaunEgan how are things on your end with 2020.2?

**Comment by ShaunEgan** [comment]
So far so good, I haven't had to change anything since updating to 2020.2.

**Comment by maartenba** [comment]
Awesome, thanks! Feel free to re-open if the problem persists. Have a nice weekend!
