### ISSUE TITLE
Sign in error for Azure Toolkit for Rider on Windows

### ISSUE THREAD

**Issue by mlabisi** [JetBrains/azure-tools-for-intellij#336]
I've started seeing this error while trying to sign in to the Azure Toolkit for Rider on Windows.
![image](https://user-images.githubusercontent.com/5050718/88953724-32d01080-d24e-11ea-98e3-6560a4d43291.png)
And [here's the log](https://github.com/JetBrains/azure-tools-for-intellij/files/5002865/idea.log)!

**Comment by sdubov** [comment]
@mlabisi, sorry for a long response. The general meaning for this error is that Java process was not able to get a necessary certificate. There are number of errors in logs related to Azure Auth when running Rider. Could you please give some more details on how do you login to Azure? What kind of login do you use - Active Directory, Device Code?

**Comment by mlabisi** [comment]
Hi @sdubov, no worries! I use the Device Login method. Before, my browser would automatically open microsoft.com/devicelogin, but now the error in the screenshot I attached pops up. I have resorted to using `az login` on the command line for now, but I do miss being able to use the Device Login method!

**Comment by sdubov** [comment]
Got it. Logs say that "AD" (Active Directory) option was selected as a login method:
`{ accountEmail: null, credFilePath: null, authMethod: AD, azureEnv: null }`. 

Let's try to fix it first. The file should be in `C:\Users\<user_name>\.AzureToolsForIntelliJ\AuthMethodDetails.json`. You can whether delete it and the plugin will allow you to login on the next start or fix it to: `{"accountEmail":"<your_email>","credFilePath":null,"authMethod":"DC","azureEnv":"GLOBAL"}`.

**Comment by mlabisi** [comment]
I've tried implementing the changes, but it looks like they get overwritten every time I start Rider ☹

**Comment by maartenba** [comment]
Are things better with 2020.2? You may want to try sign in with the Azure CLI there as well.

**Comment by mlabisi** [comment]
@maartenba That update did the trick! Thank you and @sdubov so much for your help!
