### ISSUE TITLE
Linked host.json file not recognized in configuration

### ISSUE THREAD

**Issue by CGowdy** [JetBrains/azure-tools-for-intellij#355]
There is a shared host.json file that is share amongst many projects in a solution.  VS is able to run and start all the Azure Function projects however I'm not able to run one of the projects in Rider due to the configuration not seeing a file in the project directory.

![image](https://user-images.githubusercontent.com/7138395/90678477-59b5ad00-e224-11ea-903a-95d62607c083.png)

**Comment by maartenba** [comment]
Plugin side code is now merged, there's a small change in Rider itself needed as well. https://youtrack.jetbrains.com/issue/RIDER-49556

**Comment by maartenba** [comment]
Plugin update has been released. Enjoy!
