### ISSUE TITLE
Function App project template miss icon

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#361]
<img width="321" alt="FunctionAppProjectTemplateIcon" src="https://user-images.githubusercontent.com/6064345/92302180-c47c1d80-ef72-11ea-84b9-8f4db028bece.png">

**Comment by maartenba** [comment]
Which version of the core tools do you have installed?

**Comment by sdubov** [comment]
`3.0.2881`. This is the one we install in a custom directory.

**Comment by maartenba** [comment]
This should already be fixed in `202` and `203`, but not yet in the plugin release.

![image](https://user-images.githubusercontent.com/485230/92324090-aaa80c80-f03e-11ea-9729-3e875aa8c990.png)

Can you check in `203`?

**Comment by maartenba** [comment]
Fixed in `202` and `203`
