### ISSUE TITLE
Conflict with alternate Markdown plugins

### ISSUE THREAD

**Issue by jtermine** [JetBrains/azure-tools-for-intellij#368]
I use the Markdown plugin called "Markdown Navigator Enhanced" by vladsch which I purchased.  I like for different reasons.  It conflicts with the Jetbrains standard Markdown plugin.

If I enable this Azure Tools for IntelliJ plugin, there is a hard dependency on the Jetbrains Markdown plugin.  If I don't enable it and opt instead for the one by vladsch, the entire Azure Tools plugin does not load.  So, I have to give up vladsch's Markdown plugin to use Azure Tools.  This isn't good.

There may be a hard requirement that someone uses A markdown plugin, but this shouldn't have a hard dependency on any _particular_ markdown plugin.

**Comment by maartenba** [comment]
Good catch! Markdown is actually needed for the IntelliJ version of the plugin (https://github.com/microsoft/azure-tools-for-java), but in Rider we're not using this. Let me see if I can drop the dependency...

**Comment by maartenba** [comment]
FYI I have just published an updated version of the plugin
