### ISSUE TITLE
Add Run/Debug Function App actions into Project context menu if applicable

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#382]
Currently, we use Function Gutter Mark for running Function App inside a project class. We need to understand if it might be useful to add context actions Run/Debug <Function App name> from project context menu in addition.

We need to check if project is applicable for running/debugging function app and then add those actions into the context.

Currently, we have no actions:

<img width="446" alt="AzureFunctionAppContext" src="https://user-images.githubusercontent.com/6064345/97342522-5c252a80-1897-11eb-89c2-f4da2a07fdd3.png">

Expected to have something like this:

<img width="458" alt="AzureFunctionAppContext_Expected" src="https://user-images.githubusercontent.com/6064345/97343097-22085880-1898-11eb-8935-441f6582b925.png">

**Comment by sdubov** [comment]
Please see `LaunchSettingsRunConfigurationProducer` in Rider repo.

**Comment by SeanFeldman** [comment]
Looking forward to this improvement!
Maarten gets another 🥇
