### ISSUE TITLE
F1 button should navigate to an existing plugin web app description page

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#40]
We need to make two things in scope of this ticker:
- Create a page with description
- Add `getHelpId()` handler for a `RiderWebAppSettingPanel.kt`

**Comment by maartenba** [comment]
@sdubov Is this still relevant?

**Comment by sdubov** [comment]
I think we can close it. Help in Settings navigates us to the general help page for Tools. This is a common behaviour for all settings pages. So, no changes needed.
