### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by stefanolsenn** [JetBrains/azure-tools-for-intellij#404]
Hi,
Do you have a release schedule, or know when the next version of this plugin is official released?

**Comment by maartenba** [comment]
Hi @stefanolsenn - soon!

Rider 2020.3 will be released in the coming week, and we plan to release a 2020.3 RTM of the plugin soon after. No promise as things may always change, but it looks like Dec 10 or 11.

That said, we have a Rider 2020.3 EAP version already which you can try today.

**Comment by maartenba** [comment]
Will close the issue for now, keep an eye on Rider and plugin updates next week ;-)

**Comment by stefanolsenn** [comment]
Thank you!
