### ISSUE TITLE
Run function app configuration ignores "open in browser" browser setting

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#409]
**Steps to reproduce:**
1. Create a run configuration to launch a function app
2. Set checkbox 
<img width="724" alt="OpenBrowser" src="https://user-images.githubusercontent.com/6064345/101279856-66abdb80-37d6-11eb-8201-4ec0379d38b3.png">

3. Run configuration

**Expected:** Browser is opened after starting a Run Configuration.
**Actual:** Browser is not opened.

**Comment by sdubov** [comment]
@maartenba, hm. I cannot reproduce now ob latest build from trunk. Browser is opened after I run configuration.

**Comment by maartenba** [comment]
Same here, it indeed works now. Can be closed I think.
