### ISSUE TITLE
Azure Functions: Add support for .NET isolated worker

### ISSUE THREAD

**Issue by jguadagno** [JetBrains/azure-tools-for-intellij#413]
Version [3.0.3160](https://github.com/Azure/azure-functions-dotnet-worker-preview) of the Azure Functions SDK adds support for .NET 5 within Azure Functions, via a console app.  However, the dialog box for the run/debug in Rider does not recognize the functions anymore. This is due to the Project file and executable type [changes](https://github.com/Azure/azure-functions-dotnet-worker-preview#functionapp-folder-structure) required now.

**Comment by maartenba** [comment]
Thanks for logging this one @jguadagno !

Some research from today (note to self):
* Rider Core needs updating to recognize Azure Functions .NET 5 projects [RIDER-55521](https://youtrack.jetbrains.com/issue/RIDER-55521)
* [Need to attach to innermost `dotnet.exe` when debugging](https://github.com/microsoft/vscode-azurefunctions/commit/010719623834e5c260a98d6e570f1c9a540833c0#diff-2bc50ea51ea5d338a59781c42d341917191c69156e7439388aa1ed4d83f03dcdR132)
* Quick-fixes to update project file with necessary settings would be nice to have

**Comment by maartenba** [comment]
Open items:
- [x] Project template support
- [x] Item template support
- [x] Gutter marks (run/debug)
- [x] Code completion for timer trigger schedule
- [x] Debugging
- [x] Merge changes back to 2021.1

**Comment by maartenba** [comment]
This is now available in the latest plugin version (https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider)

If you want to use isolated worker project templates, you may delete the current project template and click *Reload* to bring them in.
![image](https://user-images.githubusercontent.com/485230/118770093-36865f80-b881-11eb-9eb4-05b05b23b198.png)
