### ISSUE TITLE
Extract (most) Azure project support into Azure Toolkit for Rider

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#421]
Extract (most) Azure project support into Azure Toolkit for Rider, to reduce the amount of duplicate work for classes that currently exist in Rider and in the plugin.

Issue in RIDER: https://youtrack.jetbrains.com/issue/RIDER-55609

**Comment by sdubov** [comment]
@maartenba, the Rider issue is resolved. Can we close this ticket now?
