### ISSUE TITLE
Better error messages when auth fails

### ISSUE THREAD

**Issue by khalidabuhakmeh** [JetBrains/azure-tools-for-intellij#438]
When calling the `SubscriptionManager.updateAccountSubscriptionList` method, there is a chance that the call to Azure could fail with a few error codes.

These error codes and messages can be surfaced to help users make a decision as to what to do next.

### In Rider

![image](https://user-images.githubusercontent.com/228256/106291545-c4c6cf00-6219-11eb-9ee1-68a14fe047b0.png)

### In The Logs

![image](https://user-images.githubusercontent.com/228256/106291895-31da6480-621a-11eb-8a1c-c4ca617f4f4c.png)

**Comment by maartenba** [comment]
Note to self: somewhat related in upstream: https://github.com/microsoft/azure-tools-for-java/issues?q=is%3Aissue+is%3Aopen+ioexception

**Comment by maartenba** [comment]
All of the linked issues should be caught and shown as user-retryable/user-fixable (e.g. account error).

**Comment by maartenba** [comment]
#462
