### ISSUE TITLE
How to set run/debug configurations of Azure Functions in python project

### ISSUE THREAD

**Issue by nikonov91-dev** [JetBrains/azure-tools-for-intellij#441]
How to set up the run/debug configuration of **Azure Functions** for **Run Functions**

![Screenshot at Feb 04 23-43-55](https://user-images.githubusercontent.com/31586394/106959086-e0af0100-6742-11eb-8390-9f1efc96682e.png)

Cannot find information how to set up Azure-tools plugin for Intellij because neither Azure-tool plugin docs for python does not exist nor at [Stackoverflow](https://stackoverflow.com/questions/65170775/how-configure-azure-function-project-in-intellij-pycharm-run-debug-configuration).

I'm looking for a way to debug it in Intellij (not VSCode) but I dont know how using the tool. 

I've found docs for the [Toolkit for Java](https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/) but [there is no such for Python](https://docs.microsoft.com/en-us/azure/developer/python/)

I tried to run from the shell ```func start debug``` but it doesnt stop on debug points in Intellij.

**Comment by maartenba** [comment]
Hi @nikonov91-dev, unfortunately the plugin works only in IntelliJ IDEA on Java/Kotlin code, and in Rider on anything .NET.
I'll let the PyCharm folks know, but will close this issue for now.

As a workaround (I haven't tested this), you can try to run `func start`, wait for the process to be launched, and then [Attach To Process](https://www.jetbrains.com/help/pycharm/attaching-to-local-process.html) on the Python processes that get spawned by the Azure Functions host.

**Comment by nikonov91-dev** [comment]
I'm asking about **_Intellij_**, not PyCharm and exactly about this Azure-toolkit plugin (not any new one)
It would be nice if the team that worked on this plugin answer me how to fill in these fields.

**Comment by maartenba** [comment]
@nikonov91-dev that would be Microsoft (https://github.com/microsoft/azure-tools-for-java), this repo is our fork to support Rider
