### ISSUE TITLE
Rider 2021.1 EAP support

### ISSUE THREAD

**Issue by fearhq** [JetBrains/azure-tools-for-intellij#444]
Is it possible to update the plugin to support rider 2021.1 EAP?

**Comment by maartenba** [comment]
@fearhq Being worked on, this should be available soon (current estimate is this week, but this is not a promise ;-))

**Comment by maartenba** [comment]
@fearhq There you go :-)
https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider/versions/stable/110509

(or check plugin updates in Rider)
