### ISSUE TITLE
Cannot debug on Windows 10 when Azure Core Tools are installed with Chocolatey

### ISSUE THREAD

**Issue by jochensiegler** [JetBrains/azure-tools-for-intellij#478]
I can not debug Azure Functions Projects on 2 Machines with Windows 10.
On my Mac it works.
On the Windows Machines also run the project does work.
In debug mode i got the Error: 
"C:\Program Files (x86)\JetBrains\JetBrains Rider 2021.1.1\lib\ReSharperHost\JetBrains.Debugger.Worker.exe" --mode=client --frontend-port=54623 "--plugins=C:\Program Files (x86)\JetBrains\JetBrains Rider 2021.1.1\plugins\rider-unity\dotnetDebuggerWorker"
Process finished with exit code 0.One or more errors occurred.

**Comment by maartenba** [comment]
Thanks for reaching out @jochensiegler ! Would you have some more details for us?

* Which version of the Azure Core Tools are installed? Did you install them from within Rider, or using NPM?
* Is this a project using.NET 3.1, or .NET 5 / isolated worker?

We may need some more info, but the above should be a good start :)

**Comment by jochensiegler** [comment]
First of all, thank you for the quick answer.
I noticed it when i installed the latest version via the built in  Rider plugin management. Then I downloaded all versions that work according to the version history for 2021.1.1 and installed them manually from the downloaded zip-file.
The project is a netcoreapp3.1.
I also created a new, empty project in which there is only one http trigger

**Comment by maartenba** [comment]
That's quite strange. Would you mind emailing me on maarten at jetbrains.com so we can arrange a quick screen share? (I'm in CEST time zone)

**Comment by maartenba** [comment]
Thanks @jochensiegler for helping with troubleshooting this one!

Looks like this happens when the Functions Core Tools are installed with Chocolatey and the debugger attaches to their wrapped executable.

# Workaround

Go to Rider settings, and under `Tools | Azure | Functions`, install the functions core tools in Rider. Make sure the core tools path no longer points to the version installed with Chocolatey.

**Comment by maartenba** [comment]
## Repro steps:

1. Install Chocolatey, and the [Azure Function Core Tools
3.0.3442](https://community.chocolatey.org/packages/azure-functions-core-tools) package.
2. Launch Rider with the Azure plugin installed, and created a new Azure Functions project.
3. Debug the default run configuration
4. Observe the following output written to the debugger:

![image](https://user-images.githubusercontent.com/485230/115567297-69a5f500-a2bb-11eb-81da-65d010341080.png)

```
D:\Projects\Git\azure-tools-for-rider\PluginsAndFeatures\azure-toolkit-for-intellij\rider\build\riderRD-2021.1.1\lib\ReSharperHost\JetBrains.Debugger.Worker.exe --mode=client --frontend-port=56271 --plugins=
One or more errors occurred.
Process finished with exit code 0.
```

## Observations

* The path to the Chocolatey directory is resolved correctly.
* The tools installed with Chocolatey are smaller than the tools (with the same version) installed with NPM (where things do work)

![image](https://user-images.githubusercontent.com/485230/115567699-d4573080-a2bb-11eb-98bc-9a41f57fb248.png)

* The tools assembly guid is different (Chocolatey version vs. NPM version)

**Comment by maartenba** [comment]
In the meantime: Chocolatey installs the x86 version of Azure Functions Core Tools by default. If you install the 64-bit version, this will all work fine:

`choco install azure-functions-core-tools --params "'/x64'"`
