### ISSUE TITLE
Cannot view queues via Azure Explorer

### ISSUE THREAD

**Issue by DronVelikii** [JetBrains/azure-tools-for-intellij#495]
When I click on any action, for example "View Queue", nothing happens.
 
In frontend.log log I see the following:
`class com.microsoft.tooling.msservices.model.storage.ClientStorageAccount cannot be cast to class com.microsoft.azure.management.storage.StorageAccount (com.microsoft.tooling.msservices.model.storage.ClientStorageAccount and com.microsoft.azure.management.storage.StorageAccount are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @721934b)`

[frontend.log](https://github.com/JetBrains/azure-tools-for-intellij/files/6560502/frontend.log)

**Comment by maartenba** [comment]
An updated plugin has been released, can you try updating in Rider?

**Comment by DronVelikii** [comment]
@maartenba thanks a lot, it helped!
