### ISSUE TITLE
SSH into Web App Error

### ISSUE THREAD

**Issue by AdamCoulterOz** [JetBrains/azure-tools-for-intellij#498]
There seems to be a problem using the SSH feature for Azure Web App.

I get an error saying:

> **SSH into Web App Error**: Failed to invoke Azure CLI. Please make sure Azure CLI is installed and signed-in with same account.

![image](https://user-images.githubusercontent.com/6822248/121273461-ac736900-c90b-11eb-851c-1f4841e2ad8d.png)

I do have az cli installed, and have confirmed it is logged in with the same account. Here is the system details:

```
az --version
azure-cli: 2.24.2
core: 2.24.2
telemetry: 1.0.6

Azure Toolkit for Rider: 3.50.0.1204-2021.1
JetBrains Rider 2021.1.3
Build #RD-211.7442.29, built on May 26, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
.NET Core 5.0.5
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
```

**Comment by maartenba** [comment]
Hi @AdamCoulterOz - in Rider, can you check if you are signed in with the Azure CLI as well? (Tools \| Azure \| Sign out, then sign in, and make sure Azure CLI is selected).

Under the hood, Rider executes `az account list`, and checks if the subscription id in which the web app is hosted is in the output.

Note to self: looks like it may be a duplicate of https://github.com/microsoft/azure-tools-for-java/issues/4727 in the Microsoft upstream.
