### ISSUE TITLE
Rider doesn't start after update to latest version of this plugin

### ISSUE THREAD

**Issue by katjoek** [JetBrains/azure-tools-for-intellij#511]
**Problem**
Rider doens't start after plugin update.

**What I did**
Rider told me an update was available for the Azure ToolKit for Rider and for NSubstitute.Complete. I performed the update. After that, Rider wouldn't start any more. It hangs in the splash screen. When disabling the Azure Toolkit plugin, Rider starts again.

**What I expect**
Rider to be able to start with all installed plugins enabled

**More info**:

_Rider info:_
JetBrains Rider 2021.1.4
Build #RD-211.7628.50, built on July 13, 2021
Licensed to ***
Subscription is active until February 18, 2022.
Runtime version: 11.0.11+9-b1341.60 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, ide.tooltip.showAllSeverities=true, ide.background.tasks=false, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, search.everywhere.pattern.checking=false, ide.mac.bigsur.window.with.tabs.enabled=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, show.diff.preview.as.editor.tab=true, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, vcs.enable.add.ignored.directories.to.exclude=false, search.everywhere.settings=true, vcs.log.show.diff.preview.as.editor.tab=true, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: Abc.MoqComplete.Rider (1.4.7), Key Promoter X (2021.1.1), com.intellij.resharper.StructuredLogging (2021.1.2.140), fr.socolin.application-insights-debug-log-viewer (1.1.0), com.microsoft.vso.idea (1.161.2)

_Plugin info:_
The version information of the Azure Toolkit plugin is: 3.50.0.1234-2021.2 → 3.50.0.1204-2021.1
When I enable the plugin (without restart) and try the update button, I get an error saying 'Plugin "Azure Toolkit for Rider" download or installation failed.

I don't know where to find a log file that shows more detailed information about what went wrong.

**Comment by maartenba** [comment]
Hi, please check https://youtrack.jetbrains.com/issue/RIDER-65522 for more information. A workaround is listed here: https://youtrack.jetbrains.com/issue/RIDER-65522#focus=Comments-27-5063893.0-0
