### ISSUE TITLE
Azure Toolkit not showing up in Rider Marketplace nor can it be installed manually from disk - Macbook M1 Pro - Rider 2021.2 EAP 6

### ISSUE THREAD

**Issue by bijanmir** [JetBrains/azure-tools-for-intellij#513]
There is no support for Azure Toolkit on this version of RIDER EAP? I cannot find it on plugin marketplace nor can I install from disk when I download latest version of Azure Toolkit from the website. 

Rider EAP JetBrains Rider 2021.2 EAP 6
Build #RD-212.4638.18, built on July 7, 2021
Rider EAP User
Expiration date: August 6, 2021
Runtime version: 11.0.11+9-b1504.8 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
.NET 6.0.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1504M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, ide.tooltip.showAllSeverities=true, ide.mac.bigsur.alerts.enabled=true, show.diff.preview.as.editor.tab.with.single.click=true, ea.enable.developers.list=false, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, ide.mac.file.chooser.native=TRUE, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.mac.bigsur.window.with.tabs.enabled=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, debugger.show.values.use.inlays=TRUE, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, vcs.enable.add.ignored.directories.to.exclude=false, ide.allow.merge.buttons=TRUE, search.everywhere.settings=true, use.winp.for.graceful.process.termination=FALSE, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false, rider.enable.designer.winForms=false
Non-Bundled Plugins: com.microsoft.vso.idea (1.161.2), com.jetbrains.rider.android (212.4638.18)

<img width="986" alt="Screen Shot 2021-07-24 at 6 42 53 PM" src="https://user-images.githubusercontent.com/31123967/126885068-f9abdbc9-79fe-4ebe-8a76-0c5b127ba7a4.png">

**Comment by maartenba** [comment]
The 2021.2 version of the plugin currently supports eap7 and higher, it will indeed not install in eap6.
