### ISSUE TITLE
Unable to login through Settings | Tools | Azure | Service Authentication

### ISSUE THREAD

**Issue by mk-qa** [JetBrains/azure-tools-for-intellij#518]
JetBrains Rider 2021.2 RD-212.4746.114
Azure Toolkit for Rider 3.50.0.1253-2021.2

**STR:**
1. Open `File | Settings | Tools | Azure | Service Authentication`
2. Click "Sign In"
3. Choose "Azure CLI" or "Device Code" and click "Sign In"

**Actual:**
Nothing happens.

**Comment by maartenba** [comment]
Seems like a potential duplicate of https://github.com/JetBrains/azure-tools-for-intellij/issues/514
