### ISSUE TITLE
Plugin incompatible with Rider EAP 2021.3

### ISSUE THREAD

**Issue by vardansargsyan92** [JetBrains/azure-tools-for-intellij#522]
An early access of rider has been released with **UWP debugging** support which is nice. The bad news is that the plugin "Azure Toolkit for Rider" is not compatible with the new rider. So it would be nice to see the plugin support for rider 2021.3

**Comment by maartenba** [comment]
Literally just publishing an update :D Expect it to be live in the marketplace in ~1h

**Comment by maartenba** [comment]
Duplicates #520

**Comment by vardansargsyan92** [comment]
@maartenba  thanks a lot :-)

**Comment by maartenba** [comment]
It's up! :) https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider
