### ISSUE TITLE
web.config appears with strange 

### ISSUE THREAD

**Issue by Krangth** [JetBrains/azure-tools-for-intellij#528]
Every time I deploy to Azure app service with this plugin the deployment is always screwed up because the ASPNETCORE_ENVIRONMENT is overridden by the web.config file. Where is this configuration coming from? The web.config file does not exist on my machine. It only exists in the .zip file that is deployed. This causes the application to never be in the correct environment which results in unexpected behaviors so we always have to manually edit this file every time we update. 

How can I stop this from being added to the web.config?

```
<environmentVariables>
     <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="ExcitingLemur">
</environmentVariables>
```

**Comment by maartenba** [comment]
Is this updated in the web.config on your disk, or in the Azure environment? If you happen to have a small example solution where this happens, that would be appreciated.

**Comment by Krangth** [comment]
There is no web.config on disk.
The web.config only appears in the zip file which is created during the deployment, and then is sent to Azure. I interrupted the deployment to inspect the zip file after it was created. Once deployed, I have to use the KUDO tools to navigate to the web.config file and delete these lines as it overrides all other settings for ASPNETCORE_ENVIRONMENT

**Comment by maartenba** [comment]
Thanks, couple more questions as I have not yet managed to reproduce this:
* Do you have the value `ExcitingLemur` set anywhere in your project or run configurations?
* Is it a .NET Framework or .NET Core app, and which version?
* If you have a small project I can reproduce this with, that would be very much appreciated

**Comment by Krangth** [comment]
Can you define all the places I should look for project/run configurations? I checked in rider, the launchsettings.json, and appsettings.json. I also checked in the .csproj. I did a grepwin on the directory for the term and did not find it either. Sometimes I use ExcitingLemur as an identifier so I may have put it somewhere at some point and have no recollection of it, but I expect it would have shown up during the text search of the directory

.net core 5 app

I don't have a small project at this time. I will try to find some time to make one, but I suspect it will not demonstrate the issue as I have deployed other sites to the azure app service for different customers and never noticed this issue.

**Comment by maartenba** [comment]
I'm guessing the value will be somewhere in your project then. Any chance you can do a "find all" for that value?

**Comment by Krangth** [comment]
it is not in the project. i searched all files in the root directory. When I run the project locally I do not have that environment. It only appears when I do an azure deployment.

Is it possibly coming from the rider configuration outside of the development directory or from the machine.config or whatever those random files are called from the old days

**Comment by maartenba** [comment]
It may be in a subdirectory. Can you also try the files in the `.idea` folder?

**Comment by maartenba** [comment]
Could not reproduce this issue.

**Comment by Krangth** [comment]
I apologize for not replying. I did eventually figure it out though I don't fully remember all the details. I believe it was that my machine had an environment variable named `EnvironmentName` and even though the official documentation will say to use `ASPNETCORE_ENVIRONMENT` .net will actually automatically read from `EnvironmentName` as well during publish. I don't think I ever found any documentation about that. Thank you for your time.
