### ISSUE TITLE
2021.3 EAP gutter icon and trigger function icon not shown

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#539]
See https://youtrack.jetbrains.com/issue/RIDER-68634

**Comment by fteotini** [comment]
Sadly, it seems this issue has returned...
I'm on the latest version of both Rider and plugin

**Comment by maartenba** [comment]
Would you mind opening a new issue with some more details on project type, Rider version, SDK version, OS/architecture etc.?
