### ISSUE TITLE
Cannot create new Azure Function with Rider on MacOS

### ISSUE THREAD

**Issue by agarbutt** [JetBrains/azure-tools-for-intellij#566]
I have the `Azure Functions Core Tools` installed via `brew`.
In the settings dialog, the latest version of the functions tools are recognized (and match).
I *only* have .NET 6 SDK installed. 

I have the latest Rider (info below), launched via the latest Toolbox [JetBrains Toolbox 1.22.10970, macOS 11.6.2].
I have Azure Toolkit for Rider [3.50.0.1314-2021.3] installed. 

The Rider dialog for creating a new Azure Function, informs me that I must have the `Azure Functions Core Tools` installed and I cannot create a new Azure Function app. 

Settings Dialog Screenshot:
![image](https://user-images.githubusercontent.com/734757/151032239-ed584940-6290-4f17-8b6e-3a95d30fe87b.png)

New Solution Dialog Screenshot:
![image](https://user-images.githubusercontent.com/734757/151032503-ca840f32-995c-4e0c-bcee-6d4e94532d1a.png)

Rider Version information:
```
JetBrains Rider 2021.3.2
Build #RD-213.6461.51, built on December 22, 2021
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2
.NET 6.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 8
Registry:
    ide.new.project.model.index.case.sensitivity=true
    rdclient.asyncActions=false
    rider.enable.designer.winForms=false
    indexing.enable.entity.provider.based.indexing=false

Non-Bundled Plugins:
    com.intellij.resharper.StructuredLogging (2021.3.0.177)
    com.intellij.resharper.HeapAllocationsViewer (2021.3.0)
    com.jetbrains.rider.android (213.6461.51)
    com.intellij.resharper.azure (3.50.0.1314-2021.3)
```

**Comment by maartenba** [comment]
This should be fixed with https://github.com/JetBrains/azure-tools-for-intellij/pull/556 (2022.1 at some point)

For now, can you try grabbing the tools with Rider I stead of Brew? (Or point to the installation path where Brew downloads this specific tools version?)

**Comment by agarbutt** [comment]
Thanks for the quick reply. I am looking forward to the updated UX. 

For now, those that may stumble across this.... In my case, using the `brew --prefix azure-functions-core-tools@4` gave me a usable path for Rider to find the tools.

**Comment by agarbutt** [comment]
I will add, that however, the generated project complains of an `Invalid combination of TargetFramework and AzureFunctionsVersion is set.` 

This is an issue with the template provided by the `azure-functions-core-tools`.
It has been corrected in  [Azure Functions Core Tools Issue #2881](https://github.com/Azure/azure-functions-core-tools/issues/2881)

**Comment by maartenba** [comment]
New UX is available in 2022.1 EAP, please give it a try and see how it goes for you.

**Comment by maartenba** [comment]
Changes are in the 2022.1 EAP versions, feel free to give it a try (unless you're on an M1, then #583 is still pending)

**Comment by agarbutt** [comment]
As of 2022.1 RC, I can create Azure Function Apps v4 correctly. 
However, I cannot seem to figure out how to create Azure Function Apps based on v3.
What am I missing?

**Comment by maartenba** [comment]
Looks like the V3 and V4 templates have the same identifier, and hence only the new version is displayed. I have opened a PR with the Functions team here - https://github.com/Azure/azure-functions-templates/pull/1195

**Comment by maartenba** [comment]
Going to close this issue as v4 works properly now. Let's hope https://github.com/Azure/azure-functions-templates/pull/1195 gets accepted.
