### ISSUE TITLE
Deployment slots not appearing in the IDE

### ISSUE THREAD

**Issue by ajonno** [JetBrains/azure-tools-for-intellij#596]
everything else is great but this is really annoying. clicking on "deployment slots" will start a refresh, but when done nothing displays

**Comment by maartenba** [comment]
Is this for web apps or function apps? (Or both?) Is it a Linux or Windows app? Any additional context would be greatly appreciated.

In your `idea.log` (Help | Diagnostic Tools | Show log in [Explorer/Finder]), do you see any errors?

**Comment by maartenba** [comment]
Managed to reproduce the issue with Azure Functions. Will work on a fix,

**Comment by ajonno** [comment]
Amazing thanks for the quick response

**Comment by teneko** [comment]
Still happening. Getting visualized "Error: Deployment slot name is not provided" after selecting a subscription. Once dispalying the list of deployment slots, the list is empty, when fews days ago everything worked as expected. I only remember to have used the same profile to either disable the deployment slot or switch to another deployment slot. When adding another Azure deployment profile, the deployment slots won't appear either. In Azure Portal they exist and Visual Studio also happily sees them. :c

While browsing through the issues and find a way to delete the cache I stumbled over https://github.com/JetBrains/azure-tools-for-intellij/issues/711#issuecomment-1678592493 which indeed resolved the bug seeong no deployment slots.
