### ISSUE TITLE
Unable to run/debug Azure Function from gutter

### ISSUE THREAD

**Issue by TheAxeDude** [JetBrains/azure-tools-for-intellij#613]
Hi,

I've recently run into an issue in Rider 2022.1.2 where I no longer have the debug/run function icon in the gutter. 

I tried updating to an EAP version of rider, and got the same issue & tried adding/removing the plugin - all without success.

The project uses functions v3, netcoreapp3.1.

Please let me know if I can provide any more info!

**Comment by maartenba** [comment]
Thanks for reaching out! Just a few things to check before we dive deeper into things. Can you double check:
* Your project has a `local.settings.json` and `host.json` file
* If in the menu you go to run configurations, and run an existing Azure functions one, does that work?
* Try invalidating caches from the Rider main menu

**Comment by TheAxeDude** [comment]
Thanks a lot for the feedback - its working now.

- Your project has a local.settings.json and host.json file - **it did!**
- If in the menu you go to run configurations, and run an existing Azure functions one, does that work? - **it did!**
- Try invalidating caches from the Rider main menu -This fixed it... Sorry for not trying that first!

**Comment by maartenba** [comment]
Cool! Happy to hear that fixed it for you 😊
