### ISSUE TITLE
unable to debug Azure Function .NET Framework 4.8 AzureFunctionsCoreTools\v1

### ISSUE THREAD

**Issue by eugenevital** [JetBrains/azure-tools-for-intellij#614]
I can run the Function App but when I try to Debug I am getting this error. Looks like the parameters passed to func.exe is adding the another path\func.exe 

![image](https://user-images.githubusercontent.com/9011160/177785611-29a46171-ad4f-4d03-bbef-5877c62afa64.png)

**Comment by maartenba** [comment]
@eugenevital We don't support debugging with the v1 version of Azure Functions, sorry for that. Would you mind upgrading your project (and relevant project property) to a newer version?
