### ISSUE TITLE
Azure Functions Always Publishing Debug Code

### ISSUE THREAD

**Issue by JamesStuder** [JetBrains/azure-tools-for-intellij#628]
I have a few Azure Functions that I took over from another developer.  He used the DEBUG syntax in the code to only execute certain code if debugging or using code that was published as Debug instead of Release.  It appears that the publish function inside of Rider is always publishing with the Debug code and doesn't give you an option to choose Release during the publish process.  Also I did try to use a publish profile and I can't seem to locate how to set that up also.  The only area I could find that used publish profiles was for publish to IIS, but I can't choose my function app project in the list as it doesn't appear.

The way I am publishing is by right clicking on the project.  Choose publish and then Azure.  Once the configuration is setup then I just run it from the list of configurations, but again with this process I can't choose whether to publish release or debug code.

**Comment by maartenba** [comment]
You can use the toolbar first to select the debug/release configuration. The publish process will take into account what you have selected there. 
![image](https://user-images.githubusercontent.com/485230/185990580-cb7494b1-2152-43ed-b7c2-c58ff16c6dec.png)

**Comment by JamesStuder** [comment]
@maartenba THANK YOU!  I had a feeling it was something I was doing.  Still learning Rider.
