### ISSUE TITLE
How to sign in into Azure government cloud

### ISSUE THREAD

**Issue by metgens** [JetBrains/azure-tools-for-intellij#629]
Hi,
I was trying to sing in into Azure US government cloud using Rider and Azure tools and I could not find the way how to do this.

When I click Sign in, I have only two options available:
- Device login
- Service principal

Both of them is trying to connect to Azure using the link https://microsoft.com/devicelogin. When to connect to the US government you have to use link https://microsoft.com/deviceloginUS. 

Visual studio has instruction for that: https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-connect-vs. But I cannot find something similar in Rider.

And I also do not know why Azure CLI option is disabled. Especially that I am connected in a console to the Azure US government.

Is it possible to connect to the Azure US government using Azure-tools-for-Intellij ?

**Comment by maartenba** [comment]
Hi @metgens ! This should work following these instructions:
https://github.com/Azure/azure-docs-sdk-java/issues/751#issuecomment-457802176

Then use device login after restarting Rider.

**Comment by metgens** [comment]
Thank you @maartenba. It works. One detail in MacOs the folder where you need to create w new file has name **.AzureToolsForIntelliJ** (with dot on the beginning).

**Comment by maartenba** [comment]
Great to hear! Enjoy ☺️
