### ISSUE TITLE
Generated function.json missing direction out

### ISSUE THREAD

**Issue by AllyssaLBatten** [JetBrains/azure-tools-for-intellij#631]
**Problem**

I am attempting to deploy an Azure Function via Rider. The function is triggered by an IoT Hub message, parses the data into json, and writes it to a Cosmos database. 

When deploying this function, the generated `function.json` is missing the out direction on the generated Cosmos bindings. Everything else is correct. 

Below is the C# code and bindings section of `function.json` with sensitive data replaced with placeholder values.

**_C# Code:_**

```
using Newtonsoft.Json.Linq;
using IoTHubTrigger = Microsoft.Azure.WebJobs.EventHubTriggerAttribute;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Logging;

public static class IoTHubToCosmosDB
{
        [FunctionName("IoTHubToCosmosDB")]
        public static void Run(
            [IoTHubTrigger("eventHubName", Connection = "connectionString", ConsumerGroup = "consumerGroup")] string myIoTHubMessage,
            [CosmosDB("databaseName", "collectionName", ConnectionStringSetting = "connectionString", CreateIfNotExists = true, PartitionKey = "/deviceId")] out object dataDocument,
            ILogger log)
        {
            log.LogInformation($"C# trigger Azure function processed a IoT Hub message: {myIoTHubMessage}");
            var parsedMessage = JObject.Parse(myIoTHubMessage);
            dataDocument = parsedMessage;
        }
}
```

**_Bindings from generated function.json:_**
```
"bindings": [
    {
      "type": "eventHubTrigger",
      "connection": "connectionString",
      "consumerGroup": "consumerGroup",
      "eventHubName": "eventHubName",
      "name": "myIoTHubMessage"
    },
    {
      "type": "cosmosDB",
      "connectionStringSetting": "connectionString",
      "createIfNotExists": true,
      "partitionKey": "/deviceId",
      "databaseName": "databaseName",
      "collectionName": "collectionName",
      "useMultipleWriteLocations": false,
      "useDefaultJsonSerialization": false,
      "name": "dataDocument"
    }
  ],
```

**Environment**
_Azure Toolkit for Rider_ 3.50.0.1314-2021.3
_Azure Functions Core Tools_ 4.0.4785
_JetBrains Rider_ 2021.3.4

**Comment by maartenba** [comment]
Hi @AllyssaLBatten Unfortunately this output is not under our control and generated by the Azure Functions SDK. Would you mind opening this issue at https://github.com/Azure/azure-functions-core-tools instead? Thank you 🙏

**Comment by AllyssaLBatten** [comment]
> Hi @AllyssaLBatten Unfortunately this output is not under our control and generated by the Azure Functions SDK. Would you mind opening this issue at https://github.com/Azure/azure-functions-core-tools instead? Thank you 🙏

Will do! Thank you for the suggestion
