### ISSUE TITLE
Add an "Azure Change Feed" option when creating an Azure function

### ISSUE THREAD

**Issue by sbyzova** [JetBrains/azure-tools-for-intellij#634]
Please add an "Azure Change Feed" option when creating an Azure function, that correctly scaffolds a change feed project inside a solution.

**Comment by maartenba** [comment]
We should have this right now. The CosmosDB trigger can be used in this case:

![image](https://user-images.githubusercontent.com/485230/195523439-cb106dd4-e3a7-4449-b689-2782b24b2b84.png)
