### ISSUE TITLE
Unable to sign in with Rider

### ISSUE THREAD

**Issue by panicoenlaxbox** [JetBrains/azure-tools-for-intellij#649]
Hello,

I have JetBrains Rider 2022.3.1

I cannot sign in with device flow due to internal security constraints, so it's not an option for me.

I have tried the third option (choosing a file with service principal credentials), but nothing happens, neither error nor message, simply window closes and I continue not logged.

![image](https://user-images.githubusercontent.com/1210159/210101834-093cb910-0a58-4779-8682-a0f4d7b48d32.png)

The chosen file is something like this:

```json
{
  "appId": "612b13c5-5862-4f3d-a0e0-857d21af998b",
  "displayName": "azure-cli-2022-12-30-18-13-44",
  "password": "PASSWORD_GOES_HERE",
  "tenant": "TENANT_GOES_HERE"
}
```

It has been generated with the following commands:

```
az login
az account list --output table
az account set --subscription TENANT_GOES_HERE
az ad sp create-for-rbac > sp.json
```

Moreover, I am logged with Azure CLI, it's clear, but Rider is not able to see it. I have used az login even from the console inside Rider (however, I suppose this is not important).

![image](https://user-images.githubusercontent.com/1210159/210101730-017e75f4-ef32-43b3-8914-21de9e4b199c.png)

Thank you and happy new year!

**Comment by maartenba** [comment]
Unfortunately, a known issue - https://github.com/JetBrains/azure-tools-for-intellij/issues/514

Work is being done but for now device flow is the way to go I'm afraid.

Also best wishes to you for 2023!
