### ISSUE TITLE
Rider 2023.1 EAP 1 makes corelibs.log grow infinitely

### ISSUE THREAD

**Issue by JensSchadron** [JetBrains/azure-tools-for-intellij#657]
System info:
Macbook Pro M1
MacOS Ventura 13.1
Rider 2023.1 EAP 1
Azure Toolkit for IntelliJ 3.50.0.1550-2023.1

I noticed this issue a few days ago after running out of diskspace on my M1 macbook as the corelibs.log file kept growing without any size limits. This can be seen in the screenshot below, where the file was already 366 gigs until it ran out of disk space (after freeing up some space, it ended up growing till just over 400 gigs.)
![image](https://user-images.githubusercontent.com/10922456/215996162-35cd4d26-b22a-4e93-ab66-62bca80bd8f2.png)

The file was growing constantly due an exception being thrown every so often, but I noticed while creating this issue that a newer version for this plugin was available so I guess that the root cause of the exception is already resolved in the meantime.

Anyways, it would be neat if some sensible size constraints could be set for the file so it doesn't grow this big in a future :)

**Comment by maartenba** [comment]
~Whoa! Haven't seen this one yet. Would you mind pasting some of the entries from that log file? I see a lot of the Azure DevOps plugin entries in there on my machine but want to make sure that is also what you are seeing - so we can find the right folks to look at it.~
~(privately via maarten @ jetbrains .com works as well)~

Working on a fix

**Comment by JensSchadron** [comment]
Unfortunately I had to delete the log as other applications wouldn't open anymore, I'll keep an eye on it in the next few days on whether it actually starts growing again or not.

**Comment by maartenba** [comment]
No worries, will bake a new plugin version this week which will keep the file size low.
