### ISSUE TITLE
Azure Functions: Publish using wrong dotnet version

### ISSUE THREAD

**Issue by andy-hugecalf** [JetBrains/azure-tools-for-intellij#661]
Hi!

I'm having an issue with this plugin when publishing a net6.0 project to a function app. I recently upgraded the function app to net6.0 which came with the runtime change from ~3 to ~4. I followed the upgrade guide provided by Microsoft to do this. However, when I publish the code from Rider it changes the Function App runtime version back to ~3. I then have to go onto Azure and manually change it back. This doesn't happen for colleagues who are on the same Rider and plugin version.

When I run the publish, I see the following line in the output:
`Verifying runtime is 'dotnet' (version '~3')`

When my colleague publishes, they see (as expected):
`Verifying runtime is 'dotnet' (version '~4')`

I have tried manually installing Azure Functions Core Tools and the changing the paths for v2, v3 and v4 (in Settings/Tools/Azure/Functions) the from "Managed by Rider" to the path of the newly installed tools. This didn't change anything.

The csproj file has the following lines in it
`<TargetFramework>net6.0</TargetFramework>`
`<AzureFunctionsVersion>V4</AzureFunctionsVersion>`
`<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />`

I have set `FUNCTIONS_EXTENSION_VERSION` to `~4` but everytime I publish it gets set back to `~3`

Rider Version 2022.3.2
Plugin Version 3.50.0.1546
Core Tools Version 4.0.4915

Any ideas of what is wrong?

Cheers!

**Comment by maartenba** [comment]
Looks like the publish run configuration may have that value cached. Could you try editing your run configurations and then remove the publish configuration you currently have? This forces the cache to be removed.

Alternatively, in either `.idea/workspace.xml` or `.idea/runConfigurations/{the one you use for publishing}.xml`, find the entry for `AZURE_FUNCTION_APP_RUNTIMEVERSION` and set it to the correct one.

**Comment by andy-hugecalf** [comment]
> Alternatively, in either .idea/workspace.xml or .idea/runConfigurations/{the one you use for publishing}.xml, find the entry for AZURE_FUNCTION_APP_RUNTIMEVERSION and set it to the correct one.

This did the trick. You're a legend, cheers!

**Comment by maartenba** [comment]
Will look into making the cache a bit less aggressive as well, but glad to hear this fixed it for you. Cheers!
