### ISSUE TITLE
Azure function "run" icon is gone

### ISSUE THREAD

**Issue by Bandgren** [JetBrains/azure-tools-for-intellij#667]
Hi!

I have some intermittent issues ever since i started using Rider and the Azure plugin is that the "run/debug" icon is missing next to the function function. 
![SCR-20230306-ezc](https://user-images.githubusercontent.com/53816703/223150049-8c41f56a-7ddc-4301-93b8-c057ef615ad7.png)

Rider version: 2022.3.2
Plugin version: 3.50.0.1546-2022.3

I think i have seen an issue about this long ago but cannot find it atm sadly.

Best regards

**Comment by maartenba** [comment]
@Bandgren this is fixed in 2023.1 EAP, for other versions a File | Invalidate Caches... is a workaround that may help. Let us know if that helps.

**Comment by Bandgren** [comment]
@maartenba that fixed the issue! Thank you so much!

**Comment by iant-ee** [comment]
I'm afraid I'm still seeing this in 2023.1.1

File > Invalidate Caches with just "ReSharper Caches" didn't fix the problem. I tried again ticking all four boxes and the gutter icons reappeared.

**Comment by Bandgren** [comment]
@maartenba same here! :(

**Comment by maartenba** [comment]
Does cleaning caches resolve the issue for you?

**Comment by Bandgren** [comment]
Yes, but it keeps coming back time to time, is the acceptable workaround just to clear it and call it a day if it's a hard problem to solve?

**Comment by maartenba** [comment]
It's the acceptable workaround indeed. Not ideal that you're facing this at all, so one we'll look into with future updates 👍

**Comment by Bandgren** [comment]
> It's the acceptable workaround indeed. Not ideal that you're facing this at all, so one we'll look into with future updates 👍

Sounds good @maartenba, will close it and that we consider it a acceptable workaround for now! Have a great week!
