### ISSUE TITLE
Running/Debugging Functions Fails

### ISSUE THREAD

**Issue by Robula** [JetBrains/azure-tools-for-intellij#669]
Rider 2023.1 EAP 7 -- 231.7864.80
Azure Toolkit for Rider 3.50.0.1567-2023.1

---------------

Running or Debugging a function locally from within Rider fails.

1. ![image](https://user-images.githubusercontent.com/15246425/223440461-d5b9cc13-bf4c-4def-88ab-67702345d71a.png)
2. Build succeeded.
3. Get a notification with content:
'void com.jetbrains.rider.runtime.DotNetExecutable. (java.lang.String, com.jetbrains.rider.model.RdTargetFrameworkId, java.lang.String, java.lang.String, boolean, boolean, java.util.Map, boolean, kotlin.jvm.functions.Function2, java.lang.String, java.lang.String, boolean, com.jetbrains.rider.runtime.DotNetRuntimeType)'

![image](https://user-images.githubusercontent.com/15246425/223439815-ad1c3f46-b366-4b93-903e-90525b69f2a2.png)

https://youtrack.jetbrains.com/issue/RIDER-90685/Running-Debugging-Azure-Functions-Fails

**Comment by maartenba** [comment]
Fixed with https://github.com/JetBrains/azure-tools-for-intellij/pull/666/commits/2244e09530bf2783071dd5f702367a01b6df3b09, will be released later this week.
