### ISSUE TITLE
Vulnerable software installed: Apache Commons Text 1.8 

### ISSUE THREAD

**Issue by SOFSPEEL** [JetBrains/azure-tools-for-intellij#672]
Vulnerable software installed: **Apache Commons Text 1.8** 

Please upgrade as my company forcing removal of the toolkit as a result of this vulnerability

**Comment by maartenba** [comment]
Which version of Rider and the toolkit are you using? We did update this a while ago (2022.3 version) https://github.com/JetBrains/azure-tools-for-intellij/commit/b5b01d3a87ac6e533f3d145894f03a7664aeaedb

**Comment by SOFSPEEL** [comment]
@maartenba Thx, for the quick support, missed the fact that I was on an older Rider version, now updated, so will close this item.
