### ISSUE TITLE
Azure Functions: Make error "Specify a Node.js interpreter correctly" more clear when attempting to start Azurite

### ISSUE THREAD

**Issue by kmcgill88** [JetBrains/azure-tools-for-intellij#680]
I am unable to run my Azure function locally with the error `Specify a Node.js interpreter correctly`. I can still run the function if I use the CLI directly. I've removed the plug-in, and added it back; I have even deleted Rider and reinstalled and I'm still having this issue. Any direction would be greatly appreciated! 

<img width="477" alt="specifynode" src="https://user-images.githubusercontent.com/1992370/233188944-10b91df6-a173-499d-b4a4-4f17f1ef44d2.png">

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1992370/233188279-c6619d97-7e5e-4c47-8797-1ea0f3a70b63.png">

JetBrains Rider 2022.3.3
Build #RD-223.8836.53, built on March 20, 2023
Runtime version: 17.0.6+1-b653.34 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
.NET 7.0.0 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 1500M
Cores: 12
Metal Rendering is ON
Registry:
    ide.experimental.ui=true
    rdclient.asyncActions=false
    vcs.empty.toolwindow.show=false
    indexing.enable.entity.provider.based.indexing=false
    database.show.search.tab=false
    ide.new.project.model.index.case.sensitivity=true
    platform.projectModel.workspace.model.file.index=false
    ide.workspace.model.rbs.as.tree=false

Non-Bundled Plugins:
    com.intellij.lang.jsgraphql (4.0.0-222)
    org.sonarlint.idea (8.1.0.65508)
    **com.intellij.resharper.azure (3.50.0.1546-2022.3)**

**Comment by maartenba** [comment]
Will look into this and see if I can trap that error message. It seems to originate from trying to run Azurite - could you check if Azurite is configured in the settings? I think this should work around the issue for you.

**Comment by kmcgill88** [comment]
Doh! I didn't even know this existed! I changed it to a valid install of nodejs and things are working again. Thanks for the quick response.

<img width="968" alt="image" src="https://user-images.githubusercontent.com/1992370/233380867-590bb4a9-88d2-4db7-a285-853e80b5d482.png">

**Comment by maartenba** [comment]
Thanks for confirming! Will get it fixed though :) But happy to hear you are unblocked.
