### ISSUE TITLE
Azure Web App/Function App Deployments not working without solution file

### ISSUE THREAD

**Issue by selalipop** [JetBrains/azure-tools-for-intellij#681]
No combination of selections/shortcuts/etc. allows progress from this screen

<img width="642" alt="image" src="https://user-images.githubusercontent.com/17497673/233217456-620040f2-44f3-4539-a9e1-4ffc5112591f.png">

Manually inspecting the file, the web app info is not selected despite being selected in the UI.

Waiting for staging slots to load doesn't fix, neither does reinstalling plugin.

**Comment by maartenba** [comment]
@selalipop Would you mind reaching out to maarten at jetbrains .com so we can ask some additional info?

**Comment by devsleeper** [comment]
Any update on this?  Experiencing the same,  happy to provide any information necessary! **2023.2**

**Comment by maartenba** [comment]
@devsleeper Would you mind reaching out to maarten at jetbrains .com so we can ask some additional info?
