### ISSUE TITLE
Listener for function is unable to start

### ISSUE THREAD

**Issue by stefan-at-ilionx** [JetBrains/azure-tools-for-intellij#686]
Hi all!

Starting the debug configuration successfully builds the Azure Function, but then I'm greeted with this error message:

`The listener for function 'FunctionName' was unable to start. Azure.Core: Response was not set, make sure SendAsync was called.`

Debugging in Visual Studio works fine, which is why I thought the problem lies with the Azure Toolkit. What's weird, is that running the `func.exe` directly in the terminal seems to work:

`C:\Users\username\.AzureToolsForIntelliJ\AzureFunctionsCoreTools\v3\3.47.1\func.exe host start --pause-on-error`

**Comment by maartenba** [comment]
Can you double check the Azurite storage emulator is running? Can you share a screenshot/more context perhaps?

**Comment by stefan-at-ilionx** [comment]
Yes, the Azurite storage emulator is running. The software I'm using:

- Rider 2023.1.1
- Azure Toolkit 3.50.0.1595-2023.1
- Azure Core Tools 3.0.4899
- Function Runtime 3.17.0.0

Little sidenote: I had to install the Azure CLI myself and had to authenticate myself through the CLI. This wasn't possible with the Azure Toolkit (that option was grayed out while trying to login). Azure Toolkit still says I'm "currently not signed in with Azure CLI", even though the Azure CLI says I'm authenticated. I believe this is some other unrelated bug, though, as I've read somewhere on YouTrack.

This is really only how far I'm getting. Sharing a screenshot is obviously no problem, but it would just show the error message I shared before.

**Comment by maartenba** [comment]
Might still be useful. A Help | Collect logs would be even nicer (but I'd recommend not posting it on GitHub, feel free to send to maarten@jetbrains com though)

**Comment by maartenba** [comment]
As a side note, this seems worth trying https://stackoverflow.com/a/75392682/95901

**Comment by stefan-at-ilionx** [comment]
Already tried that, didn't work unfortunately. And the fact that debugging does work in Visual Studio (and when manually executing `func.exe` in Rider's terminal) makes it seem like our current version of `System.Diagnostics.DiagnosticSource` isn't an issue.

**Comment by maartenba** [comment]
We run `func.exe` under the hood, now I'm wondering of you encounter this issue when running in Rider without attaching the debugger?

Meanwhile, checking your logs, thanks for those! 🙏
