### ISSUE TITLE
Azure Functions App Deployment Broken by 2023.2

### ISSUE THREAD

**Issue by devsleeper** [JetBrains/azure-tools-for-intellij#705]
No combination of selections/shortcuts/etc. allows progress from this screen:

![ScreenShot](https://i.imgur.com/49xpO4h.png)

Reinstalling the plugin does not solve the issue.  
It's persistent in telling me I need to select the app despite the app being selected in the UI.

Happy to supply any information necessary! 

(Related?)  #681

**Comment by maartenba** [comment]
Duplicates #681 indeed. Moving discussion there.
