### ISSUE TITLE
Unable to Launch, Debug on ARM MBP, Rider 2023.2 (RD-232.8660.212), Az Toolkit 3.50.0.1639-2023.2

### ISSUE THREAD

**Issue by MRRQX** [JetBrains/azure-tools-for-intellij#706]
On Friday, 2023.08.04, I was using Rider, Az Toolkit to develop, debug Az Functions (Isolated) without issue.

On Sunday, 2023.08.06, I upgraded Rider to 2023.2 and Az Toolkit to 3.50.0.1639-2023.2.

Today I am unable to run, debug the same Az Function.

I use the CLI, Rider and Visual Studio Code.

Azure Functions Core Tools were initially installed using Homebrew.

`func --version`
`4.0.5198`

`brew --prefix azure-functions-core-tools@4`
`/opt/homebrew/opt/azure-functions-core-tools@4`

`which func`
`/opt/homebrew/bin/func`

I uninstalled and reinstalled Az Toolkit.

When I look at the default value for the settings:

`v2`, `v3`, `v4` = `Managed By Rider`

Download Path: `/Users/[ME]/.AzureToolsForIntelliJ/AzureFunctionsCoreTools`

If I attempt to debug using an `Azure Functions Host` profile, the Toolkit will attempt to install the tools but they are not installed to `/.AzureToolsForIntelliJ`.

<img width="460" alt="image" src="https://github.com/JetBrains/azure-tools-for-intellij/assets/122307265/89e65336-da24-45f8-a542-34b0e9e19274">

I then receive the following Rider error:

<img width="631" alt="image" src="https://github.com/JetBrains/azure-tools-for-intellij/assets/122307265/f6465d60-2631-4cf1-a486-c429d9e5fd03">

If I attempt to explicitly set the `v4` tools path to `/opt/homebrew/opt/azure-functions-core-tools@4` or `/opt/homebrew/Cellar/azure-functions-core-tools@4/4.0.5198`, the change is not persisted. It reverts once I save then reopen Settings.

If I open Terminal, execute `func start`, I am then able to attach a debugger.

**Comment by maartenba** [comment]
Looks like this is https://github.com/JetBrains/azure-tools-for-intellij/pull/702 - we're working on a new plugin version (due later this week). Thanks for reporting!

**Comment by maartenba** [comment]
FYI a fresh release has been published, you can install it from Rider's plugin manager.
