### ISSUE TITLE
After Upgrading Rider to Latest Version and Plugin To Latest Version Debug for .NET Framework not working

### ISSUE THREAD

**Issue by JamesStuder** [JetBrains/azure-tools-for-intellij#710]
I have a client that uses .NET Framework 4.8.1 for Azure Functions.  Debugging was working without having to attach the debugger in previous release.  With the latest release of Rider (2023.2) and latest release of the plugin (3.50.0.1663-2023.2) debugging for .NET Framework has stopped working.  Debugger will not turn on and I am also unable to attach the debugger to the running project.

**Comment by maartenba** [comment]
This may be related to the fix for https://github.com/JetBrains/azure-tools-for-intellij/pull/702. Will investigate, thanks for reporting!

**Comment by maartenba** [comment]
@JamesStuder A fresh version was just pushed into marketplace, can you try with the updated version of the plugin?

**Comment by JamesStuder** [comment]
That did it.  Thank you.
