### ISSUE TITLE
Azure Plugin for Rider does not detect Azure subscription 

### ISSUE THREAD

**Issue by ajxcodes** [JetBrains/azure-tools-for-intellij#711]
Hi team, 

I currently have access to an Azure subscription and up until a few days ago, I was able to publish my ASP.NET Web API project to an Azure app service. As of right now, I am no longer able to see any Azure resources and the plugin says I have no subscription but I see my subscription when accessing the Azure Portal on the web.

JetBrains Rider 2023.2 Build #RD-232.860.212  
Azure Toolkit for Rider 3.50.0.1664-2023.2
Ubuntu 22.04.3 LTS (Lubuntu) VM

![image](https://github.com/JetBrains/azure-tools-for-intellij/assets/3229158/f6b6cb27-da29-4587-bbd8-6b9d2d525f6a)

**Comment by maartenba** [comment]
Can you try to log out from the Tools | Azure menu, and log in again?

**Comment by ajxcodes** [comment]
I have tried that already.
Steps:
1. Tools > Azure > Azure Sign Out
2. Signed in using Device Login
3. And I get the screenshot below afterward.
![image](https://github.com/JetBrains/azure-tools-for-intellij/assets/3229158/22168573-5fb0-41e3-8078-8332884c3d1f)

**Comment by rlinyard** [comment]
I have this issue, too. Note: I have both company and personal logins for Azure (using the same email address). So, I get this prompt when logging into Azure (and I always have):

![image](https://github.com/JetBrains/azure-tools-for-intellij/assets/7939296/5777d216-bb2c-47cb-88b3-944ce1563705)

Note: it is my Personal account that I use for this deployment.

**Comment by rlinyard** [comment]
I was able to eventually login successfully to the appropriate subscription in the Azure Explorer pane in Rider. Don't know why it started working - lots of sign in, sign out, flush cache in Rider, restart IDE, etc. Sorry - wish I could provide exact steps but I don't dare log out and start over :(

**Comment by maartenba** [comment]
Thanks for reporting! And for your extra insights.

The multiple tenants with one email address are indeed a known issue. We are reading the plugin on Microsoft's upstream Repo where this should be fixed, however no ETA on when we'll be ready :-(

**Comment by ajxcodes** [comment]
@maartenba, thanks for the follow up! 

My workaround is to setup an Azure DevOps build pipeline triggered by a commit to a specific branch that results in a build artifact. which then triggers a deployment to the Azure resource.

**Comment by maartenba** [comment]
Duplicates #676

**Comment by chrisonoo** [comment]
Any solution, unfortunately I have the same problem and the message `No subscription` 🤔
