### ISSUE TITLE
Azure toolkit for rider block the settings screen access.

### ISSUE THREAD

**Issue by Pycnomerus** [JetBrains/azure-tools-for-intellij#717]
installed Azure toolkit for rider version 3.50.0.1679-2023.2 
on JetBrains Rider 2023.2.1
Build #RD-232.9559.61, built on August 22, 2023

every time I try the Settings menu as well as plugin menu / nugget menu stop showing.

I even tried on as new install. same result.

the only workaround I found to deactivate the plugin : help -> diagnostic tools ->  Analyze plugin Startup Performance.

and deactivating specifically the Azure tool for rider from the dropdown.

**Comment by maartenba** [comment]
Some workarounds for disabling in https://github.com/JetBrains/azure-tools-for-intellij/issues/714. The latest update no longer has this issue (but a workaround may be needed to install it)
