### ISSUE TITLE
Add slots for web app and functions deploy/preview

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#72]
From https://blog.jetbrains.com/dotnet/2018/10/16/deploy-web-apps-explore-resources-introducing-azure-toolkit-rider/#comment-530620

> Add slots for web app deploy/preview

We can now already explore slots, deploy should be added as well

**Comment by maartenba** [comment]
https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider#comment=30704

**Comment by BobBoba** [comment]
Hi there, any news about slots support while publish? Very need that feature, because by now I need to open VS and publish from there 8(

**Comment by maartenba** [comment]
Not yet, sorry @BobBoba

**Comment by wenkepaul** [comment]
> We can now already explore slots, deploy should be added as well

Could you clarify `We can now already explore slots`?  I'm able to see MyApp in the Azure Explorer tab (AzureExplorer > Azure > App Service > Function Apps > MyApp), but nothing is displayed under MyApp.  In Azure, I can see:

- Function Apps
  - MyApp
    - Functions
    - Proxies
    - Slots
      - ... List of slots
        - Functions
          - MyFunction1
          - MyFunction2

**Comment by maartenba** [comment]
...for web apps, not yet for function apps. 

@sdubov is this one we can look at for 2020.2?

**Comment by sdubov** [comment]
Yes, that's in my list.

**Comment by maartenba** [comment]
https://twitter.com/MarcBeavan/status/1286624011917692928
