### ISSUE TITLE
Not compatible with rider 2018.3 EAP

### ISSUE THREAD

**Issue by waterfoul** [JetBrains/azure-tools-for-intellij#74]
This plugin is not installable in the latest EAP

**Comment by sdubov** [comment]
@waterfoul, we plan to make a plugin build for Rider 2018.3 EAP near RC build.

**Comment by maartenba** [comment]
Plugin is available for 2018.3 now.
https://blog.jetbrains.com/dotnet/2018/12/03/work-databases-azure-cloud-shell-azure-toolkit-rider-2018-3-eap/
