### ISSUE TITLE
Add support for Azure functions

### ISSUE THREAD

**Issue by sdubov** [JetBrains/azure-tools-for-intellij#78]
We need to provide support for Azure functions:
- Azure Explorer
  - Functions: Create new function apps in Azure explorer #87
  - ✅ Functions: list function apps in Azure explorer #86 
  - ✅ Functions: Start, stop, restart the function app #88 
  - ✅ Functions: View and edit function app settings #89 
  - ✅ Functions: Deploy #150 
- Local development
  - ✅ Functions: Development: Project templates #151 
  - ✅ Functions: Development: Item templates #152 
  - ✅ Functions: Development: Run configuration for Azure Functions host #161

**Comment by maartenba** [comment]
And publish (similar to web apps probably)

For debugging, check https://twitter.com/tonesattwood/status/984611950066675712 - original issue: https://youtrack.jetbrains.com/issue/RIDER-11628

Also check Azure Functions core tools - creating new project and functions from command line: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local

**Comment by maartenba** [comment]
For runningV2 functions (on Windows):

![image](https://user-images.githubusercontent.com/485230/47338433-22adf900-d698-11e8-9bcd-bdd2751ff5c3.png)

Executable: `C:\Users\maart\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\func.exe`
Arguments: `host start --port 7071 --pause-on-error`
Working directory: `project folder\bin\Debug\netstandard2.0`

Environment:
`AZURE_FUNCTIONS_ENVIRONMENT=Development`
`AzureWebJobsStorage=UseDevelopmentStorage=true`
`AzureWebJobsScriptRoot=<working directory from earlier>`

Debug seems to hang.

**Comment by maartenba** [comment]
Did some additional research, here is how the debugger can be attached in Rider 2018.3 (https://www.jetbrains.com/rider/eap):

* Install the `func` command line tools using NPM (https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local)
* Add a file `Properties/launchSettings.json`, with the following contents (tailored to your project):

```
{
  "profiles": {
    "functions": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "%APPDATA%\\npm\\node_modules\\azure-functions-core-tools\\bin\\func.dll host start --port 7071 --pause-on-error",
      "environmentVariables": {
        "AZURE_FUNCTIONS_ENVIRONMENT": "Development",
        "AzureWebJobsStorage": "UseDevelopmentStorage=true"
      }
    }
  }
}
```

* Run the launch profile, and wait for the functions host to say it is running
* In Rider, attach to the process using **Run | Attach to Process...**. Find the process that is running `dotnet ... func.dll`:

![image](https://user-images.githubusercontent.com/485230/48606135-11969600-e97f-11e8-8769-eae56b1a6c50.png)

* Put a breakpoint somewhere and invoke a function

!!! Careful when stopping the functions process: needs a `Ctrl+C` to stop (in the Run tab), otherwise it will keep the port in use for future launches.

**Comment by skotl** [comment]
Fantastic - thanks, @maartenba! I didn't know about launch profiles, but your post along with https://blog.jetbrains.com/dotnet/2018/11/08/using-net-core-launchsettings-json-rundebug-apps-rider/ got me up and running 😃 
One other thing that took me a few minutes to figure out is to click on the Run tab once the debugger is running so that you can CTRL-C func.exe from there.
It's not seamless, but it is now definitely usable!

**Comment by maartenba** [comment]
Note to self: https://youtrack.jetbrains.com/issue/DEXP-434058

**Comment by marc-wilson** [comment]
It would be nice if this (ability to debug) was added to PyCharm too. Azure Functions support Python in addition to DotNet (some other languages as well). It's a big turn off that I can't debug the python azure function. I see there's a way to do it with Visual Studio code, but I'm not having any luck with it.

**Comment by sdubov** [comment]
I think the main work here is done. We have skipped the #87 in 191 release - there is still opened ticket for web apps with similar functionality - #46. I assume we can separate this work and move it out from the ticket scope.

**Comment by benbelow** [comment]
@sdubov Was support for v1 functions added, or just v2?

**Comment by maartenba** [comment]
@benbelow Only v2

**Comment by benbelow** [comment]
:'( Until v2 functions get service bus trigger support my team will be unable to migrate. Are there any plans to add v1 support? Or will I need to keep using Visual Studio for running functions?

**Comment by maartenba** [comment]
Looks like V2 has SB trigger support? https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#packages---functions-2x

**Comment by marc-wilson** [comment]
Any insight into how to debug this in PyCharm? I can run `func start` and the function runs just fine. However, I can't debug anything. I can, however, do run > attach to process and then I can debug.

What would an easy debug setup look like? What is the recommended way to debug Python in Azure Functions in IDE's that aren't VS Code? I would like to not have this be a two step-process. I just want to hit the debug button and go from there.

I ran into [this](https://github.com/Azure/azure-functions-core-tools/wiki/Enable-Debugging-for-language-workers), but it doesn't seem to work

**Comment by maartenba** [comment]
Right now this is only supported in Rider

**Comment by marc-wilson** [comment]
@maartenba What are the plans for it? It currently works in Rider with c#/f#, it works in WebStorm with Node/TS, it appears to work in IntelliJ for Java. The only language/product missing is Python.

Is there an open issue/feature that I can refer to for Pycharm?

**Comment by maartenba** [comment]
Not currently - this repo is mostly about the  Rider plugin. I'll ping the PyCharm folks and see if they have something to add.

**Comment by marc-wilson** [comment]
@maartenba Did you hear anything back from the PyCharm team? It'd be nice to get some sort of work around for the time being. I'm sure there's a way to configure pycharm to automatically attach itself to the process, but it's not all that clear how to do it the "python way"

**Comment by maartenba** [comment]
@mswilson4040 Did you try attaching PyCharm remote debugger to the port set in [the func example for Python](https://github.com/Azure/azure-functions-core-tools/wiki/Enable-Debugging-for-language-workers)? (I'm assuming yes based on the original question)

Best way to go is to open an issue at https://youtrack.jetbrains.com/issues/PY and provide some repro steps so the team can chime in.

**Comment by marc-wilson** [comment]
Yes, but the dialog that shows the instructions on how to do the remote debugging don't make a lot of sense. In addition, this configuration makes it seem that it's only to attach to a port, not actually run the function.

I'll move over to the youtrack page as you suggested. Thanks for your help, @maartenba

**Comment by marc-wilson** [comment]
Created https://youtrack.jetbrains.com/issue/PY-40493 for anyone else having troubles with PyCharm.

**Comment by maartenba** [comment]
Thanks @mswilson4040 !
