### ISSUE TITLE
Azure Explorer Stuck accessing Web and Function Apps

### ISSUE THREAD

**Issue by wakelt** [JetBrains/azure-tools-for-intellij#782]
**Using Azure Toolkit for Rider:  3.50.0.1755-2023-3**

Trying to get a list of azure apps using Azure Explorer. Seems Explorer has an issue providing the list, and seems to be stuck in refresh trying to get them. See attachment. Please address. 

![Screenshot 2024-02-02 at 2 38 22 PM](https://github.com/JetBrains/azure-tools-for-intellij/assets/3287632/f504fa65-8c11-444d-89de-d53440b953f9)

thanks

**Comment by maartenba** [comment]
Would you mind giving it a try with https://github.com/JetBrains/azure-tools-for-intellij/discussions/777 ?

**Comment by wakelt** [comment]
Tried #777.  It does address the issue of getting "stuck" trying to access resources. However, now I can not deploy.

![Screenshot 2024-02-03 at 10 43 36 AM](https://github.com/JetBrains/azure-tools-for-intellij/assets/3287632/c8590602-5a6a-4b21-aa20-21effa7dd1ea)

I am not sure what "name" is being referenced by the error message ?? Thus don't know how to address.

I am trying to deploy to a current web app (one that already exists). I would expect the new deployment to simply overwrite the current. Let me know if this type of functionality isn't supported.

**Comment by maartenba** [comment]
@rafaelldi Looks like this needs double checking on the V4 preview

**Comment by rafaelldi** [comment]
@wakelt Hello! Please check preview 2, it should be fixed there.

**Comment by wakelt** [comment]
I won’t be able to try until this Friday. I will let you know

**Comment by rafaelldi** [comment]
Feel free to reopen if it doesn't work for you.
