### ISSUE TITLE
Syntax highlighting abruptly stops in a Bicep file

### ISSUE THREAD

**Issue by wilsncc** [JetBrains/azure-tools-for-intellij#807]
Hi 👋🏻 

I use Intellij IDEA for Java and also for Azure Pipelines and Bicep. I have the Azure Tools for IntelliJ plugin installed and when I view certain Bicep files, the syntax highlighting will end part of the way through the file:

![image](https://github.com/JetBrains/azure-tools-for-intellij/assets/6267329/a492aaea-7635-4fe9-99aa-15b6a28b0612)

Deleting certain lines around the area where it stops will then cause more of the code to be rendered with syntax highlighting, but again it will stop not long after, generally within say 50 more lines.

This is quite distracting 🙂 Am I doing something wrong? Or could this well be a bug.

Thanks,

Ross

**Comment by rafaelldi** [comment]
Hi! This is Azure Toolkit for Rider repository. For IntelliJ IDEA, you should create an issue in this repo https://github.com/microsoft/azure-tools-for-java.
