### ISSUE TITLE
App settings for deploying web apps and functions - enhancements to 4.0 preview

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#848]
In the 4.0 preview, currently it is possible to add configuration key/values for publishing (app settings). There are 2 enhancements that would be very useful here.

1. Collapse the key/value control by default. If I have a secret in there, right now it is always shown (also when doing demos/screen recording/...). Collapsing this list by default would be an easy yet effective way of "hiding" these secrets.

2. When deploying, the settings in Azure are always overwritten by the deployment. It would be good to have a toggle to opt-in to overwriting, so configuration changes made in the Azure portal are not overwritten by local version (by default)

**Comment by rafaelldi** [comment]
I decided to remove the app settings from the deployment configuration because it's pretty error-prone
