### ISSUE TITLE
Support EAP versions of Rider

### ISSUE THREAD

**Issue by ddieppa** [JetBrains/azure-tools-for-intellij#849]
Im using **Rider 2024.2 EAP 6**  **Build** `#RD-242.19890.25`, built on July 4, 2024
and the **Azure Toolkit for Rider** version `3.50.0.1773-2024.1`
and Im getting the following error:
`Incompatible: requires IDE build 241.* or earlier.`

Is there any way to for the plugin to be able to work or a change have to be done and a new version have to be installed?

**Comment by KerryXEX** [comment]
Was just facing the same issue and found the solution in a discussion below on 4.0 update:
On plugins selection page, click on cogwheel and select "Manage plugin repositories", then add:
https://plugins.jetbrains.com/plugins/preview/list

After that, the update/prerelease of Azure plugin will appear and work as expected.

**Comment by rafaelldi** [comment]
Yes, unfortunately, due to some technical issues, only as a preview right now. We will publish the release version in the near future
