### ISSUE TITLE
[4.0] Unable to deploy function app from standalone project

### ISSUE THREAD

**Issue by Grimeh** [JetBrains/azure-tools-for-intellij#862]
Hi there!

UPDATE: this only happens when opening a standalone `.csproj`, creating a wrapper `.sln` allows you to successfully deploy a function app. This issue is specifically about the inability to deploy from a standalone `.csproj`.

After installing the 4.0 preview I cannot deploy our function app.

When creating a deploy configuration, the app settings are correctly pulled down, but I see `Error: Choose a project platform` at the bottom of the panel:
![image](https://github.com/user-attachments/assets/451a40d2-b5a1-4557-88f1-e040af4b3131)

I have tried both:
- `Tools/Azure/Deploy to Azure Functions...`
- `right click -> Deploy` on a function app in the Azure Explorer

I was able to deploy to this target with 3.50.0 (though I ran into #861), and can deploy with VS Code's Azure extension.

Let me know if you'd like logs and I can provide them (I just didn't have the time today to comb through and redact confidential info sorry).

**Comment by rafaelldi** [comment]
Hello! You should be able to see the values in that field, is there anything in it?:
![image](https://github.com/user-attachments/assets/708ac600-0af0-4cad-8af2-42c067b66793)

**Comment by Grimeh** [comment]
Ah apologies, I should have specified that in the original post. The `Configuration` field has no values.

**Comment by rafaelldi** [comment]
Perhaps you don't have any [build configuration](https://www.jetbrains.com/help/rider/Build_Configurations.html)? What do you see in the configuration manager?

![image](https://github.com/user-attachments/assets/91b534f0-432e-4c16-86e6-6914693ed85c)

![image](https://github.com/user-attachments/assets/9ff4629e-1bc9-4d4c-91a2-3d79cb540637)

You can also check other Publish configurations if they have values in the `Configuration` combo box.

![image](https://github.com/user-attachments/assets/45b425cb-a5c4-41f9-8761-99f0ec2bad43)

![image](https://github.com/user-attachments/assets/49611d23-7827-4a07-90dd-734d4c05aaec)

**Comment by Grimeh** [comment]
I'm not sure if it's because I'm not on the EAP (which your screenshots seem to be from), but I don't seem to have a dedicated configuration manager. I can see Debug & Release configurations in the project properties though, but they seem to be a different type of configuration.

![image](https://github.com/user-attachments/assets/f7cc4358-6647-4df2-9155-4a92ec518ad2)

![image](https://github.com/user-attachments/assets/04f7270a-3e00-4abe-b3ae-7c614e29cb6f)

As suggested, I checked another publish configuration and "Publish to folder" has the same problem.
![image](https://github.com/user-attachments/assets/bed9096b-ebad-49bc-bfbd-eccc3b59b4c7)

**Comment by Grimeh** [comment]
So I noticed that our setup doesn't actually have a `.sln`, just a standalone `.csproj`.
Without a solution I suppose there aren't any solution configurations 😅 
I will attempt to create a wrapper solution to see if that resolves the issue.

Is this an intentional restriction? Pre-4.0 doesn't require a solution, neither does VSC's plugin.

**Comment by Grimeh** [comment]
Creating a wrapper solution did indeed fix the issue (I can also see & edit solution configurations now).

I'll update the title & OP to reflect the info that it only happens when opening a standalone `.csproj`.

**Comment by rafaelldi** [comment]
Thank you, fixed that

**Comment by Grimeh** [comment]
Legend, thanks!
