### ISSUE TITLE
Publishing my Azure Function removed all my function's app settings and now gives a java.lang.Object error

### ISSUE THREAD

**Issue by MeltdownInteractive** [JetBrains/azure-tools-for-intellij#867]
I had Azure Toolkit for Rider publishing perfectly fine last night.
Today I published again, and get the following error when publishing 

_Trying to deploy artifact to stage...
**Failed to proceed. Unsupported text Content-Type Type: class java.lang.Object.**_

I noticed in the Azure Portal on my Stage Azure Function, that all the App Settings in my Function Environment Variables were removed and replaced with the single default environment variable 'SCM_DO_BUILD_DURING_DEPLOYMENT' in the Rider publish window. 

**Azure Portal**
![image](https://github.com/user-attachments/assets/77140a65-222c-4afb-95ee-01ac5c1c3a16)

**Rider Publish Window**
![image](https://github.com/user-attachments/assets/93b4c62d-db51-4822-9e74-4ffa3a122e2e)

**Toolkit Version**
4.0.0-preview.6

**Rider Version**
JetBrains Rider 2024.1.4
Build #RD-241.18034.76, built on June 24, 2024
Licensed to Greg Quinn
Subscription is active until August 12, 2024.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v8.0.1 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4084M
Cores: 32
Registry:
  ide.experimental.ui=true
  terminal.new.ui=true
  ide.new.project.model.index.case.sensitivity=true
Non-Bundled Plugins:
  Dart (241.18808)
  com.jetbrains.rider.android (241.18034.76)
  com.intellij.resharper.azure (4.0.0-preview.6)

**Comment by rafaelldi** [comment]
Hello! Thank you for the report. This has already been fixed. Run configuration won't change the application settings during the deployment. This should be available in the next release. Feel free to reopen if this doesn't help.

**Comment by MeltdownInteractive** [comment]
@rafaelldi May I ask when the next release is expected to become available? Thanks

**Comment by rafaelldi** [comment]
Most likely this week.

**Comment by MeltdownInteractive** [comment]
@rafaelldi Is there a reason why the stable release of Azure Toolkit for Rider is only available for Rider preview builds (242+) ?
I'm trying to install the toolkit 4.0.2 but even after updating Rider to 2024.1.6 I can't install it. When will it support stable releases of Rider?

**Comment by rafaelldi** [comment]
@MeltdownInteractive What do you mean by Rider preview builds? The current version Rider 2024.2.1 is a stable release and plugin is supported there. Version 4.* of the plugin won't be available for Ride 2024.1 and earlier. Plugin versions 3.* are available for these versions of Rider.

**Comment by rafaelldi** [comment]
You can check the supported products of a particular version on the marketplace page

https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider

![image](https://github.com/user-attachments/assets/e4a9302a-a1a7-4275-9fcf-1ab81c5e9eb2)

**Comment by MeltdownInteractive** [comment]
> @MeltdownInteractive What do you mean by Rider preview builds? The current version Rider 2024.2.1 is a stable release and plugin is supported there. Version 4.* of the plugin won't be available for Ride 2024.1 and earlier. Plugin versions 3.* are available for these versions of Rider.

@rafaelldi 
Perhaps I misunderstand how Rider's 'check for updates' work. I would assume 'check for updates' would automatically install the latest stable Rider version for me and install 2024.2, not stay stuck on Rider 2024.1

Interestingly I just checked for updates again now, and 2024.2 is now being suggested, when I did an update check 2 days ago it only updated to 2024.1.
