### ISSUE TITLE
This Azure PlugIn update is no longer able to Login to Azure (4.0.1)

### ISSUE THREAD

**Issue by sergiolindolfoferreira** [JetBrains/azure-tools-for-intellij#884]
Hi JetBrains,

Today I updated Rider and Azure SDK PlugIn (4.0.1) and stopped being able to Login to Azure.

Azure: Failed to load subscriptions. Exception java.lang.UnsatisfiedLinkError: Unable to locate JNA native support library [in thread "pool-14-thread-1"].
Call Stack:
● Load subscriptions
● Reload subscriptions
● Login with (OAUTH2)
● Sign in to Azure

**Comment by rs2pt** [comment]
Same here...
- latest Rider updates (arm version)
- MacOS / MacbookPro M3

**Comment by rafaelldi** [comment]
Sorry for that. As a workaround you could use the `Azure CLI` login.

![image](https://github.com/user-attachments/assets/c6961fad-7332-4314-bbf8-8587905e4e30)

**Comment by rs2pt** [comment]
Hi @rafaelldi 
I don't have that option available 🤔
![Screenshot 2024-08-16 at 11 48 29](https://github.com/user-attachments/assets/443ead72-10f6-4e13-ba1b-021e35f30679)

**Comment by rafaelldi** [comment]
Do you have the Azure CLI installed?

**Comment by rs2pt** [comment]
😅 sorry didn't have installed. 
Logged by CLI now, thanks!

**Comment by sergiolindolfoferreira** [comment]
We already have the publications for Azure working.

Thank you

**Comment by rafaelldi** [comment]
I'm still going to fix this problem, so I'm reopening it

**Comment by rafaelldi** [comment]
Unfortunately, the error `Unable to locate JNA native support library` occurs due to a third-party library that is used for authentication in Azure. As a workaround, it is possible to use `Azure CLI` login or disable the authentication cache in Settings.

![358579349-ecf8a00c-f7ff-4b26-9806-28db56504dc6](https://github.com/user-attachments/assets/3012bc14-7ac3-496d-a744-bc9a3248425d)

**Comment by inseokjoo** [comment]
I had the same issue today, and it happened after updating Azure toolkit 4.0.2 and Rider 2024.2.
I installed the Cli and logged in, and it's working fine now.
I'm really glad you found this issue.
Thanks.👍

**Comment by lexuanzhou** [comment]
Also for some reason I am not able to see the the database connection tab anymore after i updated to rider version 2024.2
<img width="819" alt="image" src="https://github.com/user-attachments/assets/fd97a9af-6435-4009-848c-bf7cd931bce8">
vs
<img width="785" alt="image" src="https://github.com/user-attachments/assets/515dd737-31e5-48f1-9bec-1b1c49ed7932">

stuck at the deployment step
<img width="1387" alt="image" src="https://github.com/user-attachments/assets/2092438f-8459-47bb-adfb-e63b1d362c2a">

**Comment by rafaelldi** [comment]
@lexuanzhou This is because this feature isn't supported yet in the v4 version of the plugin. I've created a ticket for that #897

**Comment by nilsanderspersson** [comment]
Why is database creation missing, and why does it say RUNTIME: Unknown? Have you released a version that isn't finished? It's a major issue if this version isn't complete and there's no way to roll back to version 3.
