### ISSUE TITLE
Function classes are not being identified after update to 4.0.0/4.0.1

### ISSUE THREAD

**Issue by divieirasilva** [JetBrains/azure-tools-for-intellij#891]
Not sure if it's "by design", but I want to contribute in case it is not. 

It seems that the Azure Toolkit can no longer detect when a class is used as a function. Before the update to version 4.0.0, this "suggestion" was not shown.

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/3d5d58b3-d55e-4ad7-8fcd-4e5ff2bdc86d">

**Comment by maartenba** [comment]
@rafaelldi These came from https://github.com/JetBrains/azure-tools-for-intellij/tree/232/PluginsAndFeatures/azure-toolkit-for-intellij/rider/resources/dotnet/Extensions/com.intellij.resharper.azure/annotations (needs to be in that folder)
