### ISSUE TITLE
Azurite configuration is reset with each plugin major update

### ISSUE THREAD

**Issue by TechWatching** [JetBrains/azure-tools-for-intellij#895]
I have configured my Azure settings on rider to have a custom Azurite workspace instead of one managed by Rider. However, some times when the plugin is updated, this configuration is lost which is a bit disturbing because the workspace becomes the default one managed by Rider.

![image](https://github.com/user-attachments/assets/011e52a7-54bd-4f50-ac3a-90fcb0c166ed)

**Comment by rafaelldi** [comment]
Hello! I've made a change to save the Azurite settings in the `.idea` folder for each solution. Unfortunately, after this change they will be restored again with default values, but after that they will be saved in the solution folder and should not be changed for different versions of Rider.
