### ISSUE TITLE
Functions: view log stream

### ISSUE THREAD

**Issue by maartenba** [JetBrains/azure-tools-for-intellij#90]
Similar to web apps. Connect to log stream and show in Rider. https://azure.microsoft.com/en-us/resources/videos/log-streaming-with-azure-web-sites/

**Comment by sdubov** [comment]
Created related ticket - [RIDER-48520](https://youtrack.jetbrains.com/issue/RIDER-48520)

**Comment by sdubov** [comment]
I've checked this with recent 202 upstream merge - #328. Function App log stream works. I think we can add this feature into 202.
