### ISSUE TITLE
Default Changed - Publish to Azure app service now deletes user files

### ISSUE THREAD

**Issue by APinchofDill** [JetBrains/azure-tools-for-intellij#902]
**Version**
v4.x

**What is happening:**
All files deleted then the new files are published, app service is restarted. Past versions of the plugin did not delete files of the app service on publish.

**What should happen**
On publish the dlls and exe files are updated and the app service is restarted. User files remain.

**Comment by nilsanderspersson** [comment]
We have had such significant issues with version 4 and publishing to the Azure App Store that our entire team has had to revert to using Visual Studio

**Comment by rafaelldi** [comment]
It should be fixed with #904

**Comment by APinchofDill** [comment]
@nilsanderspersson Downgrading to Rider 2023 latest and that azure toolkit 3.50.0.1755-2023.3 version of the plugin works solid. I have found 2024 rider / plugins to be a bit more RC'esque and not currently great for production coding. The jetbrains team is solid and their products always seem to stabilize and 2024 has some great updates but I would just wait a bit longer until the team stays on 2024.

**Comment by APinchofDill** [comment]
@rafaelldi Thank you for your work on this.
