### ISSUE TITLE
Azure Toolkit not compatible with Rider 2024.2

### ISSUE THREAD

**Issue by magsto-ffcg** [JetBrains/azure-tools-for-intellij#903]
When upgrading Rider to the latest version 2024.2.2 it's not possible to create or run Azure fucntion apps anymore. The latest Azure Toolkit for Rider v 3.50.0.1784-2024.1 is installed. The Run/Debug Configurations editor shows an error that the plugin may not be compatible. This is a bit annoying that the toolkit project can't be in sync with the latest official release of Rider.

**Comment by magsto-ffcg** [comment]
Ok, I found it, there is a v 4.1 of the plugin that can be installed. However the older run/debug configuration was not compatible. A bit annoying to re-create it for every function I have (multiple functions in multiple projects company-wide...). But I close this because the initial problem is solved.

**Comment by rafaelldi** [comment]
Yes, unfortunately we have some breaking changes due to a major release. If you have a `launchSettings.json` file, the run configurations should be generated automatically
