### ISSUE TITLE
Misleading tooltip for incorrect NCronTab expression

### ISSUE THREAD

**Issue by ivanskorikov** [JetBrains/azure-tools-for-intellij#913]
The tooltip states that only six field format is supported:
<img width="1294" alt="image" src="https://github.com/user-attachments/assets/5a64782f-0768-4621-be93-dd6acc716da3">

However, [Azure docs state](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2,isolated-process,nodejs-v4&pivots=programming-language-csharp#ncrontab-examples) that five field format is supported as well:

<img width="861" alt="image" src="https://github.com/user-attachments/assets/e0b0b4d2-6b35-443a-8a4c-7cf2ca29561b">

Five field format strings are not highlighted as an error as expected, however the tooltip displays incorrect information.

**Comment by rafaelldi** [comment]
Thank you for the report!

**Comment by rafaelldi** [comment]
This exception comes from the NCrontab itself. But both five-part format `* * * * *` and six-part format `* * * * * *` are parsed without exceptions. I'm not sure if we want to change the error message for this particular case.

https://github.com/atifaziz/NCrontab/blob/master/NCrontab/CrontabSchedule.cs#L121

![image](https://github.com/user-attachments/assets/ec6559f7-4680-4bc2-950e-098e34534ea9)

![image](https://github.com/user-attachments/assets/fd82a5e8-2313-4ec0-8ced-8603d4688bd7)
