### ISSUE TITLE
Is there a preview version compatible with Rider 2024.3 EAP?

### ISSUE THREAD

**Issue by DeveloperMMB** [JetBrains/azure-tools-for-intellij#935]
Hi,

Currently trialing Rider 2024.3 EAP 3 however I am unable to use Azure Toolkit plugin (4.2.0) due to it wanting an earlier version of Rider. I've have added https://plugins.jetbrains.com/plugins/preview/list as a plugin repository but still can't find a compatible version.

Will there be a version released that is compatible with Rider 2024.3 EAP or will we need to wait for Rider to be released officially? 

Thanks,

Mikey

**Comment by rafaelldi** [comment]
Hello! No, unfortunately, there is no release available for 2024.3. We are planning to publish a release for this version, probably in two weeks.
