### ISSUE TITLE
Running functions results in No Azure Functions Core Tools information could be determined

### ISSUE THREAD

**Issue by Codex-** [JetBrains/azure-tools-for-intellij#939]
Azure Toolkit version: 4.2.2
Rider: 2024.2.6
OS: MacOS 15.0.1
.net: 8.0.403

When attempting to upgrade a function project from dotnet 6 (v3) to dotnet 8 (v4) we found that attempting to run the function in Rider resulted in the error:

```
Can't run Azure Functions host. No Azure Functions Core Tools information could be determined
```

We've attempted various things on this particular project (ensured that `AzureFunctionsVersion` is set correctly in the csproj, etc) and found this same error occurs on new projects generated with rider too.

Rider is configured to self-manage everything, including dotnet versions, az versions, etc.

Recreation steps:

- Create a new Azure Functions project with all default settings

<img width="651" alt="image" src="https://github.com/user-attachments/assets/679caeee-0be8-42f8-aa13-bb9dba591380">

- Attempt to run this project, with no changes results in:

```
Can't run Azure Functions host. No Azure Functions Core Tools information could be determined
```

<img width="451" alt="image" src="https://github.com/user-attachments/assets/1c4e66c2-af19-4f6e-b68b-9efa1cb0a9e4">

If the generated new project results in this, I'm unsure where I could be going wrong. Is there anything else I could be missing?

**Comment by rafaelldi** [comment]
Thank you for the report! I'll take a look

**Comment by fabiocav** [comment]
Hi @rafaelldi,

I’m with the Azure Functions team.

It’s possible that recent changes in the tooling feed may have impacted your experience, assuming that's what you're using. As a precaution, we’ll be reverting those changes. Would you be the best point of contact for coordinating future updates and communication with us?

Looking ahead, we’re looking to establish a better-documented process for IDEs to support Azure Functions. Our goal is to make this experience smoother and more reliable.

Thanks!

/cc @mattchenderson

**Comment by mattchenderson** [comment]
That revert is now complete. Hopefully that helps address this!

**Comment by rafaelldi** [comment]
@fabiocav 

Thank you very much for the information!

> Would you be the best point of contact for coordinating future updates and communication with us?

Yes, you can contact me in case of any changes.

> Looking ahead, we’re looking to establish a better-documented process for IDEs to support Azure Functions. Our goal is to make this experience smoother and more reliable.

That sounds really great, thank you!

**Comment by rafaelldi** [comment]
@Codex- Could you please check if everything is working fine now?

**Comment by Codex-** [comment]
@mattchenderson @rafaelldi my apologies, was meant to update you both yesterday.

Tested locally and with some colleagues on their respective machines and we're all going now! Thank you so much for the fast resolution :)

Worth noting if anyone finds this in the wild and is still finding issues, sometimes you can end up with various globally installed versions for places like brew and npm, etc, nuking these and either using this plugin + rider, or installing the singular instance gets you going again too

Thanks again, team

**Comment by rbnswartz** [comment]
I'm still running into this problem, what part of the toolchain should I be updating? Core tools, nuget package, rider plugin, or something else?

**Comment by rafaelldi** [comment]
@rbnswartz Rider should automatically download the latest version of the core tools (4.97.0). Do you have it locally?

<img width="738" alt="image" src="https://github.com/user-attachments/assets/e3f6899b-3a7b-4008-bc5d-7536a554e267">

**Comment by Manuel-Innovapps** [comment]
I'm experiencing the same problem today. Tried different versions of rider, but ended up with the latest 2024.3 EAP 4 and plugin version 4.3.0 (also EAP I think).

I opened the same pane as shown above, and checked that there is a path in there. I opened this path in file explorer and deleted the v4 directory. Launching the azure function from Rider again, makes this folder reappear (assuming it got downloaded), but it still fails to run:
![image](https://github.com/user-attachments/assets/41a61fc7-f950-469e-800d-d28c341f4158)

**Comment by manuel3108** [comment]
I'm experiencing this today. I tried different rider and plugin versions, but ended up with the latest 2024.3 EAP 4 and plugin version 4.3.0 (also EAP I think).

Opend the same windows as above, opened the path displayed in my windows in file explorer, and deleted the 4 folder. Trying to launch the azure function again from within rider, indeed redownload the folder, but it still fails to start with the same exception.

**Comment by mosessaur** [comment]
I am also experiencing this issue on both 2024.2.7 and 2024.2.6

**Comment by 0xReq** [comment]
Workaround for me was removing the managed version by Rider and set path explicitly or from env path.

Using Rider 2024.2.7 and v4 func.

Azure Func Core tools is [4.0.6280]

![image](https://github.com/user-attachments/assets/663d3393-9ab6-451a-8173-60494ff3e809)

**Comment by AntSkilton** [comment]
I can confirm that I'm encountering this issue too on Rider 2024.2.7, and @0xReq's workaround is working for me.

As I have v4 installed with npm too (I didn't before I encountered this issue), I'm now using that version by selecting "From environment PATH" on the dropdown to get that.

![image](https://github.com/user-attachments/assets/52f4bbb6-26af-48da-bc71-2cc6cb42331e)

**Comment by rafaelldi** [comment]
Hello! The issue should be fixed in the 4.2.3 version. Please remove the `v4` folder inside the `{HOME FOLDER}/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/`, the plugin should redownload core tools.

**Comment by omeszar** [comment]
Hi @rafaelldi I have the latest plug installed (4.2.3). Remove the folder. The plug in, did indeed re-downloaded V4, but the error persists.

Edit: Running in Fedora.

**Comment by rafaelldi** [comment]
Yes, unfortunately, it looks like on macOS and Linux this problem still exists. I will address it on Monday. See #944

**Comment by omeszar** [comment]
Thx @rafaelldi In the mean time, I will use it as not managed by rider by installing the npm package.

**Comment by rafaelldi** [comment]
Hello, folks. Please try the new `4.2.4` version. The problem should be fixed there. We'll use the previous release of Azure core tools, and in the meantime, we'll find out what's going on with the current one.

**Comment by omeszar** [comment]
> Hello, folks. Please try the new `4.2.4` version. The problem should be fixed there. We'll use the previous release of Azure core tools, and in the meantime, we'll find out what's going on with the current one.

Thx @rafaelldi 4.24 is working with the Managed By Rider. Good luck finding the issue with the current one :)
