### ISSUE TITLE
Rider download a non-existent azure core tools release 4.99.0

### ISSUE THREAD

**Issue by JessicaA-Auror** [JetBrains/azure-tools-for-intellij#951]
Rider: 2024.2.7
OS: MacOS 15.0
.net: 8.0.403
Azure function core tools: 4.0.6280 (installed in environment path)

When pulling down new azure core tools, rider puts them under a `4.99.0` folder instead of having the correct version in there. 

Latest release in azure core tools [4.0.6543](https://github.com/Azure/azure-functions-core-tools/releases/tag/v4.0.6543): https://github.com/Azure/azure-functions-core-tools/releases 

The function does not run, error below:
`Failed to start the in-process model host. An error occurred trying to start process '/Users/<user>/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4/4.99.0/in-proc8/func' with working directory '/Users/<user>/repos/bin/Debug/net8.0'. Permission denied`

Work around is using the core tools separately and pointing to local environment path instead.

**Comment by rafaelldi** [comment]
Hello!

> rider puts them under a `4.99.0` folder instead of having the correct version in there.

It isn't a core tools release version, it is a tag from the core tools feed. You could check this repo for more information ([link](https://github.com/Azure/azure-functions-tooling-feed)).

> The function does not run, error below: `Permission denied`

I think that the `/Users/<user>/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4/4.99.0/in-proc8/func` executable doesn't have the right permissions to execute. You could check. But Rider shouldn't use that executable, it uses the one from the `/Users/<user>/.AzureToolsForIntelliJ/AzureFunctionsCoreTools/v4/4.99.0` folder. Have you changed something?

**Comment by JessicaA-Auror** [comment]
Thank you for the explanation. I've closed this issues as per the explanation above. The permission was related to the following issue : https://github.com/Azure/azure-functions-core-tools/issues/3766#issuecomment-2363989919
