### ISSUE TITLE
The plugin is unable to keep me logged on

### ISSUE THREAD

**Issue by ENez7** [JetBrains/azure-tools-for-intellij#967]
I can log in using OAuth 2.0, but as soon as I close Rider, I am automatically logged out of my account and have to redo the entire login process. Am I missing something? A few versions ago, this didn't happen at all

**Comment by rafaelldi** [comment]
Hello! Do you have this option enabled?

<img width="677" alt="image" src="https://github.com/user-attachments/assets/d2c1935e-7081-4d0d-8d18-df1354fe38d4">

**Comment by ENez7** [comment]
It works fine now, thank you, God bless

**Comment by rafaelldi** [comment]
@ENez7 Glad to hear that. Did this option `Enable autthentication cache` help you? Or did the problem just go away?

**Comment by ENez7** [comment]
Yeah, the cache resolved the problem, now I don't have to redo the login process
