### ISSUE TITLE
Can't run Azure Functions host. Unable to find locally or download Function core tools

### ISSUE THREAD

**Issue by eseger13** [JetBrains/azure-tools-for-intellij#970]
I've downloaded Rider to a new computer and I'm getting the error "Can't run Azure Functions host. Unable to find locally or download Function core tools"  on an in process project and "Azure Functions host did not return isolated worker process id" on an isolated project.

I'm using Rider 2024.3 and Azure Functions Core Tools 4.0.6610 installed globally.  I'm not seeing anything being downloaded into the C:\Users\{user}\.AzureToolsForIntelliJ\AzureFunctionsCoreTools.  I've tried a few permutations of the configuration and nothing has worked.  

I'm using Rider 2024.3 and Azure Functions Core Tools 4.0.5907 on my previous laptop and no issues.  

Should the Azure Toolkit for Rider be downloading Azure Functions Core Tools to the C:\Users\{user}\.AzureToolsForIntelliJ\AzureFunctionsCoreTools directory?  What troubleshooting steps should I try to get the host to be recognized?

**Comment by eseger13** [comment]
I tried to downgrade my global Azure Functions Core Tools install to 4.0.5907 since that's the version on the working machine, but no change after a reboot.

**Comment by rafaelldi** [comment]
@eseger13 It depends on what you have here. If it has the value `Managed by Rider`, then Rider should download them. If there is a path, then Rider will use that path and won't download them.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/c73b9c9e-bf98-4a27-9ef6-23ab5c5150e6">

**Comment by eseger13** [comment]
I have the Core Tools Path set to Managed by Rider.

<img width="515" alt="image" src="https://github.com/user-attachments/assets/93996bf4-5ad2-4a8b-8b84-27686315c666">

This is the error I'm getting.
<img width="534" alt="image" src="https://github.com/user-attachments/assets/c747df5f-fd2b-4a9a-ad6e-3451b407179d">

I've tried to uninstall and re-install Rider, Azure Functions Core Tools, the Azure Tools plugin and I can't get the host to be downloaded/discovered.  What can I try next?

**Comment by rafaelldi** [comment]
1. You can set the path to your manually installed core tools.
2. You can collect logs, create an issue in our tracker (https://youtrack.jetbrains.com/issues/RIDER) and upload them. To collect logs, please enable the Azure trace scenarios (via Help | Diagnostic Tools | Choose Trace Scenarios | Azure), reproduce the issue and collect logs (via Help | Collect Logs). I'll take a look.

**Comment by eseger13** [comment]
This is what I'm seeing for my core tools install path:
<img width="431" alt="image" src="https://github.com/user-attachments/assets/3ccbf2cf-e41c-43b9-bc5e-57aadc89936f">

I've pointed Rider to that path in my config, but no change:
<img width="466" alt="image" src="https://github.com/user-attachments/assets/69d3d597-a3a5-4be8-853d-9bcc399a978d">

I'll collect logs and send them over.

**Comment by rafaelldi** [comment]
The path should point to the executable. Something like this `C:\Users\{Your user name}\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\func.exe`; for the default worker model it should be like this `C:\Users\{Your user name}\AppData\Roaming\npm\node_modules\azure-functions-core-tools\bin\in-proc8\func.exe`.

**Comment by eseger13** [comment]
I updated to point to the .exe and it works for isolated, but not in-process.  I'll get you a log dump to see what's going wrong.  My previous computer with my Rider install is all set to "Managed by Rider" and it works for both isolated and in process.  Thanks for your help to get this resolved on this new machine!

**Comment by eseger13** [comment]
I just posted logs to YouTrack with ticket RIDER-120960

**Comment by rafaelldi** [comment]
Let's continue there (https://youtrack.jetbrains.com/issue/RIDER-120960), I will close this one.
