### ISSUE TITLE
Losing access to a selected subscription after relaunching Rider

### ISSUE THREAD

**Issue by Ephirion** [JetBrains/azure-tools-for-intellij#971]
I'm using JetBrains Rider 2024.3 Build #RD-243.21565.191 with the Azure Toolkit for Rider 4.3.5 installed. I can successfully log in with OAuth 2.0, select the required subscription (one of the two), and work. However, after relaunching Rider I can no longer access the subscription needed and can no longer choose it from the subscription selector, requiring me to log in again, which is frustrating. I'm also receiving this error message in the notifications:

<code>
Azure: Failed to get subscriptions for tenant ___________, please confirm you have sufficient permissions. Use -Dauth.tenant=TENANT_ID to explicitly login to a tenant if it requires Multi-Factor Authentication (MFA). Message: The current credential is not configured to acquire tokens for tenant ____________. To enable acquiring tokens for this tenant add it to the AdditionallyAllowedTenants on the credential options, or add "*" to AdditionallyAllowedTenants to allow acquiring tokens for any tenant. See the troubleshooting guide for more information. https://aka.ms/azsdk/java/identity/multitenant/troubleshoot
</code>

**Comment by rafaelldi** [comment]
Hello! Could you please check the setting option mentioned in this issue #967?

**Comment by Ephirion** [comment]
Hello!
Yes, I have this option enabled
![image](https://github.com/user-attachments/assets/e754a627-2ff6-4d35-9d95-5d102ff8a37f)

**Comment by rafaelldi** [comment]
Could you please submit the issue to our tracker (via Help | Report a Bug)? This action will collect logs and create a ticket here https://youtrack.jetbrains.com/issues/RIDER. It's difficult to understand what is going on without the logs.

**Comment by Ephirion** [comment]
Created the report
https://youtrack.jetbrains.com/issue/RIDER-120951/Azure-plugin-loses-access-to-a-subscription-after-relaunch

**Comment by rafaelldi** [comment]
Then I'll close the issue
